### ISSUE TITLE
"Cannot open as Archive"

### ISSUE THREAD

**Issue by TyranntX** [OpenNaja/cobra-tools#101]
Hello, I've been following your tutorial (on how to make a new species) exactly how it is shown on You Tube, but I when I try to open the OVL_Tool_Gui file with cmd it simply refuses to open and gives me a message saying it cannot be opened as an archive. I could use some help so I can start making mods too, please and thank you

**Comment by HENDRIX-ZT2** [comment]
"it cannot be opened as an archive"
What?

**Comment by TyranntX** [comment]
> "it cannot be opened as an archive"
> What?

When I'm in the cmd box in the cobra-tools-master file, and I try to use it to open the ovl_tool_gui.py, a box opens up stating (and I quote)... "Cannot open file (file location of ovl_tool_gui.py as an archive"

**Comment by HENDRIX-ZT2** [comment]
You're doing something wrong. Learn how to use the cmd.
