### ISSUE TITLE
"sizedstring" error

### ISSUE THREAD

**Issue by jjdp0** [OpenNaja/cobra-tools#102]
Hey! I am sorry if I'm wasting your time but like most people making new species, there is a common problem...

 

For me and many other modders, we get a "SizedString" error.

 

If you know a way around this, please respond to this message.

**Comment by jjdp0** [comment]
UPDATE: This error only appears when reopening the Main.ovl files after being edited/altered.
Additionally, this error may concern the deletion or incorrect alteration of a wrong file in Main.ovl.

When opening a Main.ovl...
![image](https://user-images.githubusercontent.com/65613096/110257253-02cab780-7f6b-11eb-9a13-e1b028c39dd6.png)

When injecting new files into Main...
![image](https://user-images.githubusercontent.com/65613096/110257286-2f7ecf00-7f6b-11eb-9042-7c98d005a483.png)

**Comment by HENDRIX-ZT2** [comment]
You're doing something wrong. Probably not reloading or something.
