### ISSUE TITLE
Won't Hash Path

### ISSUE THREAD

**Issue by konsaurus** [OpenNaja/cobra-tools#104]
I've followed the New Species tutorial on YT step by step. Then I have to Hash the AssetPackages which has no files but only Paths. In the tutorial, he is able to hash paths just like he did with files, but when I try to do it NOTHING happens. The command prompt only reads "Loading 0 files into gui" and NOTHING changes. I've been struggling with this for HOURS and I'm starting to lose it, I don't know what to do. Please help me

**Comment by HENDRIX-ZT2** [comment]
Latest master can hash paths and add/ remove them.
