### ISSUE TITLE
Animal Zoopedia Image doesn't register, possible deletion problem

### ISSUE THREAD

**Issue by LeafProductions** [OpenNaja/cobra-tools#109]
Yeah, I know I've said this on Discord a million times, but for my past 3/4 mods, it's happened consistently with the same UI - Animal Zoopedia Image. Attached below is what it looks like ingame, I am certain that the files are correct though, I'm doing the same process I've been doing for the past few months. 

I typically open, delete all except for llama, save, reopen after opening my dummy ovl, hash and extract, save, reopen after opening my dummy, and injecting once I finish the texture. 

![Planet Zoo Screenshot 2021 04 14 - 12 28 30 35](https://user-images.githubusercontent.com/81026426/114745760-ffbaa800-9d1c-11eb-8b37-7e165c4af2b0.png)

**Comment by HENDRIX-ZT2** [comment]
Apparently fixed.
