### ISSUE TITLE
About the animation 

### ISSUE THREAD

**Issue by Iven-Wu** [OpenNaja/cobra-tools#111]
Though the animation files .mani, .manis are shown in the folder, it cannot be imported into Blender cause it will raise some errors. How can I fix it?

**Comment by HENDRIX-ZT2** [comment]
Manis are not supported and won't be for a looooong time.

**Comment by Iven-Wu** [comment]
So is there any chance we can extract the animation of animals in Planet Zoo and load it into Blender?

**Comment by HENDRIX-ZT2** [comment]
No, only banis can be imported partly. Manis can not be read.
