### ISSUE TITLE
Loc files rearranging themselves

### ISSUE THREAD

**Issue by kemipue** [OpenNaja/cobra-tools#116]
I've noticed recently, that after I've extracted, amended, injected and saved my loc files, if I extract again to amend the information, for some reason the information is now under the wrong header on some, not all, the files.  For example, it'll say 3kg under sexual maturity age when that's the information I put under female weight, and it'll have the colour description under the scientific name.  Things like that.  It's a pain to keep fixing it, then hoping it'll stay correct.  Not sure if it's an issue with the editor or sqlite studio, or just me!

**Comment by HENDRIX-ZT2** [comment]
What version are you using? Release or latest master?

**Comment by HENDRIX-ZT2** [comment]
Sounds like a bug with the ovl tool.
Can you describe your steps exactly?
SQLite should not be involved with txt files.

**Comment by HENDRIX-ZT2** [comment]
Closing due to lack of confirmation.
