### ISSUE TITLE
Using cobra with command line in Ubuntu

### ISSUE THREAD

**Issue by Iven-Wu** [OpenNaja/cobra-tools#118]
1. Add "material_name = material_name.lower()"  in plugin/modules_import/material.py  after Line 174
2. Delete Line 14,15 (from ovl_utils ....) in generated/io.py
   Also delete parts in generated/io.py that are related to the two package mentioned in the deleted Line 14 and 15
3. Delete the parameter "operator" and "context" in "load" function in plugin/import_mdl2.py Line 18

Then only changing the filepath in load() function can work.

**Comment by HENDRIX-ZT2** [comment]
None of this makes any sense.

**Comment by Iven-Wu** [comment]
I mean with those changes mentioned above, we can using the "load" function in ubuntu, so that it can import the mdl2 file in blender for further usage.

**Comment by HENDRIX-ZT2** [comment]
It doesn't load otherwise?
How can it work if you remove operator and context? They are required by blender, even if they aren't used by the function.

**Comment by Iven-Wu** [comment]
I have no idea about that. But it does work on my computer. What about I send you the code and one video to demonstrate that?

**Comment by Iven-Wu** [comment]
I've put the code and the video on google drive. https://drive.google.com/drive/folders/1DStZ8zkFBO4STCT4STTezYk-0USwHahd?usp=sharing
The four folders shown are only needed.

**Comment by HENDRIX-ZT2** [comment]
Well that's not the intended use of the plugin. You're supposed to use it from the GUI, not from the command line

**Comment by HENDRIX-ZT2** [comment]
I've removed context & operator, blender now allows for that. I've also refactored io. But can't really remove oodle from there. Well I can refactor it a bit.

**Comment by Iven-Wu** [comment]
Oh, great! Thanks a lot.

**Comment by HENDRIX-ZT2** [comment]
I can pull out the oodle stuff too.

**Comment by Iven-Wu** [comment]
Wow, that's fantastic!

**Comment by HENDRIX-ZT2** [comment]
Oodle has been moved out too so current master should now work from ubuntu command line.

**Comment by Iven-Wu** [comment]
Whoa, that will a lot help for more blender scripts!

**Comment by zachguo** [comment]
Oodle seems to be back. I tried to install the Blender plugin on MacOS, and it threw error about missing oodle. The plugin works if I deleted all oodle related code in `generated/formats/oval/__init__.py`.
