### ISSUE TITLE
OVL - Strange Fur Appearance at LOD0 after dat editing

### ISSUE THREAD

**Issue by PlasticForked** [OpenNaja/cobra-tools#121]
**Describe the bug**
Stock male red panda gains a weird transparent fur layer/appears blurry on rename/dat edit.

**To Reproduce**
1. Copy content0 Red_Panda_Male files into ModCoons Male animal folder
2. Rename files to Raccoonss_Male
3. Open with OVL tool
4. Check New Species. Rename "red_panda" to "raccoonss"
5. Uncheck New Species
6. Rename "red_panda" to "raccooned"
5. Save and Close
6. Reopen with OVL tool
7. Check New Species, then Dat Edit: "Red_Panda" to "Raccooned"
8. Save and Close
9. Open game, purchase and place male raccoon
10. Out pops blurry red panda

**Expected behavior**
Since it's a stock animal with only rename/dat edit, and no model or texture changes, it should appear as normal. Using same steps as above on female, it looks normal. Strange they come out different.

**Screenshots**
![image](https://user-images.githubusercontent.com/86510117/123504101-7f65cc80-d614-11eb-93ae-b27598c5b33a.png)

**Version Info:**
 - Python Version: 3.9.5
 - Blender Version: 2.92 (unused here)
 - Cobra Tools Version: Master, downloaded 6.26, 12:01 AM (linked by NDP in modding-help chat)

**Comment by PlasticForked** [comment]
I've uploaded my progress [here](https://drive.google.com/file/d/1PUm4lV4TBPixxmr9ss9OBWwr3pcXPr9i/view?usp=sharing). Mod is updated to 1.6 except the male files (which are 1.5).

**Comment by HENDRIX-ZT2** [comment]
Kudos for the best bug report to date! 
I'm not sure about the problem though since I don't code new species

**Comment by HENDRIX-ZT2** [comment]
One thing to try, it might be the saving itself that breaks it. So just save stock panda and see what happens if you replace it ingame.

**Comment by PlasticForked** [comment]
Do you mean save out the stock panda and replace the stock panda with that save file? Sorry, not sure what you mean :)

**Comment by HENDRIX-ZT2** [comment]
Yes, that's what I meant. In that case it looks like you're dealing with a name issue. You renamed for two but only dat edited for one name?

**Comment by PlasticForked** [comment]
Oh is another needed? If so what should the second dat edit need to be? Also just a reminder the same steps on the female files with only the one dat edit worked.

Renames were: red_panda > raccoonss (for ms2) and red_panda > raccooned (for rest of files)
Dat edit was Red_Panda > Raccooned (to match rest of files)

**Comment by PlasticForked** [comment]
FYI I tried with the newest version of the tools, now getting a super cool silver surfer red panda lol
![image](https://user-images.githubusercontent.com/86510117/123732038-8aa83a80-d856-11eb-88ad-09194fd54138.png)

**Comment by PlasticForked** [comment]
Been trying to troubleshoot, but not really sure what I'm looking for. Noticed this in the AssetPack files when opening:
![image](https://user-images.githubusercontent.com/86510117/123892819-847a9280-d918-11eb-8c96-0d9d85d9ea08.png)

**Comment by PlasticForked** [comment]
[Dats.zip](https://github.com/OpenNaja/cobra-tools/files/6743993/Dats.zip)
Tried again with the latest tools, the male isn't silver anymore, but the same issue remains. I've attached Dat files for female (working) and male (with issue). I don't see anything that looks missed. If you have a moment to review, I'd be very grateful. I've run out of ideas to try.

Oh I also redid Animals\AssetPacks just in case. No change.

**Comment by PlasticForked** [comment]
New test today. The female files have many with "male" in the name instead of "female". I tried unpacking and injecting all those into the male file. No change. 

The only files with "female" in the name (so I didn't use) are the Manis and Motiongraph - I don't know much about those, but seems unlikely they would cause this kind of issue.

**Comment by HENDRIX-ZT2** [comment]
Current tools should no longer have this bug.
