### ISSUE TITLE
Loc.ovl planet zoo after 1.6 broken 

### ISSUE THREAD

**Issue by ANILKEN** [OpenNaja/cobra-tools#122]
Hello, I am translating for planet zoo to my country. After version 1.6 I encountered a strange error, I have no idea why this error is caused. When I save the loc.ovl file without injecting it, it happens as in the picture. The same situation happens when I inject the .txt file.

**Screenshots**
https://imgur.com/bj0WvQK
https://imgur.com/Yn2Dn8j

**Version Info:**
 - Python Version: 3.9.5150
 - Blender Version: -
 - Cobra Tools Version: Master

**Comment by HENDRIX-ZT2** [comment]
Fixed by https://github.com/OpenNaja/cobra-tools/commit/64756b38963d6eaaa8015e9ac553e35d72f8a7de
