### ISSUE TITLE
Blender 2.92 import mdl2 error

### ISSUE THREAD

**Issue by Harish-shk** [OpenNaja/cobra-tools#123]
**Blender 2.92 extracted mdl2 file import error**
When i try to open the mdl2 file format in blender...it says "unpack requires a buffer of 4 bytes." How can i fix this issue.pls help me? 

Pls tell me how to i fix it?

**Version Info:**
 - Python Version: [e.g. 3.7.2]
 - Blender Version: [e.g. 2.92 and 2.82]
 - Cobra Tools Version [e.g. release v1. 5, or master, downloaded on June 1st 2022]

**Comment by HENDRIX-ZT2** [comment]
Your tool versions? Which game? What file?
