### ISSUE TITLE
Cant seem to open the program

### ISSUE THREAD

**Issue by AnsgarTOdinson** [OpenNaja/cobra-tools#124]
**Describe the bug**
When double clicking on any of the .py files the CMD window pops up briefly then immediately vanishes.

**Version Info:**
I downloaded all the required files via the links provided but I must be missing something.  Any help would be appreciated.

**Comment by AnsgarTOdinson** [comment]
Edit.  I ran from windows power shell and got the error message

"Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings"

I do have python installed.  Even made sure to install the 3.7 from the link

**Comment by HENDRIX-ZT2** [comment]
Probably didn't add it to the path during installation.
