### ISSUE TITLE
How to unpack high quality of textures?

### ISSUE THREAD

**Issue by Harish-shk** [OpenNaja/cobra-tools#126]
When i unpack the ovl file.its just exporting the 1440*1440 resolution textures(png).how to i unpack high resolution textures?

**Version Info:**
 - Python Version: [e.g. 3.6.0]
 - Blender Version: [e.g. 2.92]
 - Cobra Tools Version [  Master, date 2022 july 2nd]

**Comment by HENDRIX-ZT2** [comment]
I assume you are trying to get detailed scale textures from JWE? They are stored as tiled textures using matcol files, which you can import into blender to visualize and bake to a high res texture.

**Comment by Harish-shk** [comment]
I can't understand.can you explain me... Pls... What i need to do?
