### ISSUE TITLE
OVLs become unusable after injection; "index out of range"

### ISSUE THREAD

**Issue by DagobahResident** [OpenNaja/cobra-tools#128]
**Describe the bug**
ovl-tool appears to work fine, until I try launching the game with the modified ovl (Jurassic World Evolution), which crashes on launch after a few seconds. When I attempt to re-access the modified ovl, ovl-tool returns an error saying the "list index out of range" before closing itself and the python command window before I can grab a screenshot.

**To Reproduce**
1. Open ovl-tool-gui.py
2. Open Main.ovl from JWE's content0
3. Inject .lua mods I want to add to the game
4. Save the new Main.ovl in the same directory it came from
5. Close ovl-tool
6. Run JWE game
7. Game crashes on launch
8. Re-open modded Main.ovl in ovl-tool
9. See error message and ovl-tool closes

**Expected behavior**
I'm following steps for lua injection outlined by tutorials, yet every injection I try has the same failed result. I'm expecting the game to launch like normal with new features provided by the mod luas. I'm also expecting the modified Main.ovl to be openable by ovl-tool after injection and saving, not returning an error that closes the tool and prevents any sort of corrective action.

**Version Info:**
 - Python Version: 3.7.6
 - Cobra Tools Version: master, downloaded 30 July 2021
 - EDIT: Worth mentioning that I tried this with different versions of Python since the code page says to download version 3.7, but the latest is 3.9.6. Versions attempted: 3.6.0, 3.7.0, 3.7.6, 3.9.6.
 
 **Log Files:**
[ovl_tool_gui.log](https://github.com/OpenNaja/cobra-tools/files/6912859/ovl_tool_gui.log)

**Comment by HENDRIX-ZT2** [comment]
Thanks for this thorough report!
Current master should have fixed this.

**Comment by DagobahResident** [comment]
I assume I don't need the Blender plugin since I'm only injecting mods, not trying to create new models?

**Comment by HENDRIX-ZT2** [comment]
> 
> 
> I assume I don't need the Blender plugin since I'm only injecting mods, not trying to create new models?

They both use the same code, and no, you don't need it. Just download and try this version: https://github.com/OpenNaja/cobra-tools/archive/refs/heads/master.zip

**Comment by DagobahResident** [comment]
Okay, that seems to have fixed it. 
I neglected to mention the other cobra tools master I had downloaded would display a lot of python errors, like not finding files or they were broken, etc. 
I also made sure to start the tool once, then close it so it would create a config.ini. No such error messages this time, I can reopen the ovl, and the game actually runs with the injected luas :)

**Comment by HENDRIX-ZT2** [comment]
Well, that is nice to hear!
