### ISSUE TITLE
New Species Tutorial update

### ISSUE THREAD

**Issue by jjdp0** [OpenNaja/cobra-tools#130]
As cobra-tools gets more and more updates, the tutorials for it will become outdated, like last time.
I suggest that new tutorials are released for cobra-tools as it will be easier for us modders to create new species with minimal issues.
The tutorials available now were uploaded many months ago and are old (especially the one for Planet Zoo).

**Comment by AwesomeJWE-P-M** [comment]
Yep

**Comment by HENDRIX-ZT2** [comment]
Out of scope.
