### ISSUE TITLE
1.6+ ovls with more than one ovs DAT break when saved

### ISSUE THREAD

**Issue by harlequinzeg0** [OpenNaja/cobra-tools#131]
**Describe the bug**
1.6+ objects/animals crash when their ovl is saved by the tools if the ovs archive has more than one day

reason is our buffergroup algorithm is not working for this case I think

**To Reproduce**
1. open a stock ovl,
2. save it
3. game crashes when object/animal is placed now

**Expected behavior**
doesn't crash

**Version Info:**
 - Cobra Tools Version: latest

**Comment by HENDRIX-ZT2** [comment]
I think this is no longer valid, is it?
