### ISSUE TITLE
Missing skeleton

### ISSUE THREAD

**Issue by filetaker** [OpenNaja/cobra-tools#134]
Help please ! When i use mdl import , i only get mesh LOD without bones. But how am i supposed to get skeleton with vertex weights

**Comment by HENDRIX-ZT2** [comment]
Tools version, mdl2 file, error log?

**Comment by filetaker** [comment]
Blender 2.92.0,  CobraTools 2.3.8, no error log. When i use mdl2 import option, the mesh is loading perfectly with all LOD and textures baked, but there are no joints. So mdl2 should load bones too and the issue is in my tv
![1](https://user-images.githubusercontent.com/89646350/131227627-d5c7fb82-4b42-44b0-8e50-6e9796d80562.jpg)

**Comment by HENDRIX-ZT2** [comment]
Upload the log file that is saved in the cobra folder inside your blender add-ons folder.

**Comment by filetaker** [comment]
[blender_plugin.log](https://github.com/OpenNaja/cobra-tools/files/7071321/blender_plugin.log)
by the way i installed 2.93.3 with same Cobra version . Thanks for the help

**Comment by HENDRIX-ZT2** [comment]
The skeleton raises errors. Is that mdl2 from the current version of planet zoo?

**Comment by filetaker** [comment]
Yes the log contains 163 bones but they are not imported

**Comment by filetaker** [comment]
Most likely it is not the current version. When i load the ovl in Editor it automatically selects pre 1.6

**Comment by HENDRIX-ZT2** [comment]
> Most likely it is not the current version. When i load the ovl in Editor it automatically selects pre 1.6

Right, that means you have to update your game. Only current version is supported.

**Comment by filetaker** [comment]
Ok thanks
