### ISSUE TITLE
Scales not importing with texture + cannot import anything but .mdl2, can't import animations or anything.

### ISSUE THREAD

**Issue by YousefYK** [OpenNaja/cobra-tools#140]
So in blender the textures do not have scales or anything.  Plus, I can't import anything but .mdl2 files. No animations, nothing.

**Comment by HENDRIX-ZT2** [comment]
Scales are on the matcols, which do work. Anims don't work.

**Comment by YousefYK** [comment]
The Matcols for me give this error.
![Screenshot 2021-11-07 163128](https://user-images.githubusercontent.com/75555691/140668074-e9a82e7e-059b-41a5-bee3-0c388aeab2ea.png)

**Comment by YousefYK** [comment]
Oh, and this too.
![Screenshot 2021-11-07 163343](https://user-images.githubusercontent.com/75555691/140668138-5765f6e2-79ad-45e8-a804-ea94674545ff.png)
