### ISSUE TITLE
Plugin - Matcols not importing

### ISSUE THREAD

**Issue by YousefYK** [OpenNaja/cobra-tools#141]
Here's the first error it gives,
![Screenshot 2021-11-07 163343](https://user-images.githubusercontent.com/75555691/140670848-39ae60a8-9c1e-4453-9415-62a6a676be3b.png)

Here is the second error it gives.
![Screenshot 2021-11-07 163128](https://user-images.githubusercontent.com/75555691/140670882-8df270a9-5c87-4a6d-937b-ea1cf8b9fce7.png)

Please help, I can't get the scales to work.

**Comment by HENDRIX-ZT2** [comment]
You have to unpack the dinosaur common ovl file into the Indominus Rex folder first. Then you can import matcols

**Comment by YousefYK** [comment]
Where are those files located?

**Comment by HENDRIX-ZT2** [comment]
Somewhere in the JWE game folder, idk.

**Comment by YousefYK** [comment]
Yeah, so I extracted it from the common files. Specifically common0, the folder. But thats all. I'll take a windows capture of it when I get home.

**Comment by HENDRIX-ZT2** [comment]
JWE2 matcols import again. Heightblendscale #79 is still pending.
