### ISSUE TITLE
Extracting luas and bins

### ISSUE THREAD

**Issue by Kaiodenic** [OpenNaja/cobra-tools#142]
Heya,

Not really sure where to "request" something that isn't a bug, sorry if this is in the wrong place - I can move it if there's a better place to post this. An old version of Cobra Tools would extract both compiled and decompiled scripts regardless of whether or not the decompilation worked fully - having both .lua for non-decompilable scripts and .lua.bin for decompiled scripts was instrumental in some of the scripting mods I made for JWE.

Since this has been removed, I just stayed using the older version for extraction - but with JWE 2 coming out, I'll need to switch to latest. Is there some toggle where I can have both extract regardless of luadec success? Barring that, could such a toggle be added? This could cut down huge amounts of time when making script mods.

Hope y'all having a good one, cheers!

**Comment by HENDRIX-ZT2** [comment]
Just check the 'save temp files' button and the bin will appear too.

**Comment by Kaiodenic** [comment]
Fantastic, thanks so much!

**Comment by HENDRIX-ZT2** [comment]
Well, if you run into compilation issues, you get the decompiled lua anyway, as long as luadec spits out any data at all.
