### ISSUE TITLE
Multiple Scripts in a New .ovl

### ISSUE THREAD

**Issue by Kaiodenic** [OpenNaja/cobra-tools#144]
There has been an issue with both recent PZ and the JWE 2 ovl tool wherein compiling a _new_ .ovl file with more than one script will cause a crash after loading into a map (but NOT when opening the game). I've been working around this by just having a dud Main.ovl call sub-ovls with one script each, but it would be very helpful to be able to compile them all into a single file.

Thanks for all your work!

**Comment by HENDRIX-ZT2** [comment]
Can you identify a version in which it still works, or provide an older created ovl with several Luas that works?

**Comment by Kaiodenic** [comment]
Sure! My version is very old so it might be hard to tell when I got it, but I'll relay all info I can after work today.

**Comment by HENDRIX-ZT2** [comment]
Like I said, any old ovl file with several luas, created from that old version, will do.

**Comment by Kaiodenic** [comment]
Here's some ovls. In case it helps, I supplied:

- Old multiple script ovl
- Old single script ovl, if there is anything helpful about the comparison
- New single script ovl

https://drive.google.com/file/d/1JEYx9GKIP8F83mPYoSQ6WKY5rOfRcVeG/view?usp=sharing

**Comment by HENDRIX-ZT2** [comment]
To verify, `Old multiple script ovl` works in game?

**Comment by Kaiodenic** [comment]
Yep, it works in-game for JWE 1.

**Comment by HENDRIX-ZT2** [comment]
Good. What I can confirm rn is that saving the old working OVL produces the identical result, while re-creating it from scratch yields a different and bigger result. Will investigate...

**Comment by Kaiodenic** [comment]
I seem to recall that , back when I did stuff, for both JWE and PZ, I could compile multi-script JWE 1 files, but _not_ multi-script PZ files - but I might be mistaken. So, if something is acting weirdly similar when re-creating then that might have something to do with it.

**Comment by Kaiodenic** [comment]
I supplied the single-script ovl in case that helps compare single vs multi-script PZ/JWE 2 files

**Comment by HENDRIX-ZT2** [comment]
I've re-created the multi-script ovl with current tools, and there are some small differences like different sorting inside the archive, could you test if that still works ingame now:
[MultiScriptRe.zip](https://github.com/OpenNaja/cobra-tools/files/7515075/MultiScriptRe.zip)

**Comment by HENDRIX-ZT2** [comment]
I think I know the issue. We are missing padding after each LUA. Is this only the case on LUAs or have you run into this issue with other file types too?

**Comment by Kaiodenic** [comment]
Cheers! I'll test it in a little bit - I'm mid-raid right now so I can't launch another game, this one can be a bit temperamental. I've only run into it with Luas, but I've only tried it with Luas too. I can try it with fdbs after raid and see how that goes.

**Comment by HENDRIX-ZT2** [comment]
I figured that. Multi-lua creation should be fixed now on master, in any case!

**Comment by HENDRIX-ZT2** [comment]
Fixed!
