### ISSUE TITLE
Having problems unpacking ovl file from Jurassic World Evolution 2

### ISSUE THREAD

**Issue by Rudolphmeister** [OpenNaja/cobra-tools#148]
I am using the latest version of Cobra Tools and I'm trying to unpack an ovl file but whenever I try to do it it's giving me an error. I tried reinstalling cobra tools but that didn't work so I'm lost. https://i.ibb.co/MNhx69n/Error.png

**Comment by ilodev** [comment]
could you specify the file you are trying to open?

**Comment by Rudolphmeister** [comment]
The issue has been fixed after reinstalling the Blender Cobra Tools.

**Comment by VelvetMelody** [comment]
please, fix the issue that the tool cant open ovls in Content 0 folder

![Image](https://github.com/user-attachments/assets/4eba8353-1e31-4e06-a86a-37cb819234aa)
