### ISSUE TITLE
.mdl2 unextractable

### ISSUE THREAD

**Issue by thijnmens** [OpenNaja/cobra-tools#149]
All mdl2 files are grayed out and unextractable, is this because of the files or something I am doing wrong?

**Note**
I am extracting files from Elite but from a version BEFORE 2.4, aka the file system is still only .ovl's and .ovs's. not that hashed encrypted bullshit it is in the current versions.

**Comment by HENDRIX-ZT2** [comment]
MS2 files export just fine, ED is not supported.
