### ISSUE TITLE
Error "Custom property 'some_index' missing..." whenever I try exporting an MDL2 File

### ISSUE THREAD

**Issue by Rudolphmeister** [OpenNaja/cobra-tools#151]
Whenever I try to export my MDL2 file it gives me the following error: 

"Custom property 'some_index' missing from Spinosaurus (data: Material). Add it!". 

I have no clue how to fix this. I already tried restarting and reinstalling.

**Comment by HENDRIX-ZT2** [comment]
Materials created on import should automatically assign the property. Make sure your plugin and OVL tool are both current master, extract from the OVL again, import that into blender again.
