### ISSUE TITLE
permission denied error

### ISSUE THREAD

**Issue by akbartalpur19** [OpenNaja/cobra-tools#153]
well im having permission denied error 
![Screenshot (178)](https://user-images.githubusercontent.com/89235972/146842276-983cf170-47c4-4bd2-a8ce-34ec0f331fd1.png)

**Comment by akbartalpur19** [comment]
also i ran blender as admin it didnt help instead of a error blender crashed

**Comment by akbartalpur19** [comment]
well im having permission erno error thats what i only know

**Comment by akbartalpur19** [comment]
![Screenshot (178)](https://user-images.githubusercontent.com/89235972/146842323-42347c77-efca-4ba6-a7e7-a5344663625d.png)

**Comment by HENDRIX-ZT2** [comment]
Don't install the plugin into the program folder, you don't have writing permission there.
