### ISSUE TITLE
FGM refactor: allowing adding textures for new fgm files

### ISSUE THREAD

**Issue by ilodev** [OpenNaja/cobra-tools#154]
The current FGM support in cobra-tools was designed to support injection mostly, hence it is litmited to what the editor can do; however, we already have create on fgms, and we are allowed to add new fgms and reuse them at will.

Ideally we would need to move from static binary export of fgm into xml, and allowing creating brand new fgms. that involves:
- creating a list of valid texture names to chose from.
- creating a list of valid attributes to chose from.
- creating a list of valid shaders to chose from.
- working on the attribute types and arguments they have to make the editor adjust to it.

Injection should still work as long as the input matches the injected entry, we can check that when loading it.

**Comment by HENDRIX-ZT2** [comment]
The fgm editor supports adding and deleting attributes and textures, we just need to collect a list of valid texture and attribute types. Can do that with the batch walker tool. And add the actual GUI button to add a new texture.
Not sure if plaintext makes this any easier for us.

**Comment by HENDRIX-ZT2** [comment]
FGMs can now be created from scratch.
Util > Inspect FGMs gets the required data from a game folder. The resulting py file is put in the hashes subfolder to access it.
