### ISSUE TITLE
Main.ovls take ages to load

### ISSUE THREAD

**Issue by bbbolec** [OpenNaja/cobra-tools#155]
First of all I want apologize for my english. I'm from Poland and my english is not vey well.
My issue is about Cobra Tool Master. When the program is running, first what I can see is the sighn which says the config.ini is missing or broken. After this the OVL Tool program runs kinda normally but when I'm tryin' to open the file (Main.ovl) it starts loading, then OVL Tool doesn't responding and loading crashes. And yes, it's about Jurassic World Evolution. Please help me. Can somebody tell me how to fix that issue?
I'm not pc master race, so please help me like i'm totally newbie with coding. Thank you, and have nice day. :)

**Comment by HENDRIX-ZT2** [comment]
Opening main OVL can take a long time, depending on your PC. Try animal OVLs to see if your installation works.

**Comment by bbbolec** [comment]
> Opening main OVL can take a long time, depending on your PC. Try animal OVLs to see if your installation works.

So I opened other OVL file, and it worked, but the Main.ovl looks like crashing when i'm tryin' to open it. I'll try to wait for open it correctly. How long +/- should I wait for the results then?

**Comment by HENDRIX-ZT2** [comment]
This is due to the new prefab code. Will need to be optimized...
