### ISSUE TITLE
Jurassic World Evolution 2 

### ISSUE THREAD

**Issue by Fatmax13** [OpenNaja/cobra-tools#156]
Dear Maker

Could you add the game mentioned in the title to the tools?

Best Regards

**Comment by HENDRIX-ZT2** [comment]
Current master supports JWE2.

**Comment by Fatmax13** [comment]
Currently not visible in the game list .     https://kepkuldes.com/image/JWh7SA

**Comment by HENDRIX-ZT2** [comment]
Yes, because you're not using the current master:
https://github.com/OpenNaja/cobra-tools/archive/refs/heads/master.zip

**Comment by Fatmax13** [comment]
thx
