### ISSUE TITLE
Texture Injection Not Working properly? (JWE2 Centric)

### ISSUE THREAD

**Issue by DeviljWheat** [OpenNaja/cobra-tools#157]
**Describe the bug**
Whenever you open an OVL of any creature in JWE 2, injecting a new texture will cause the program to say not enough values to unpack (expected 2, got 1).

**To Reproduce**
1. Go to the Cobra Tools Master Folder
2. Click on ovl_tool_gui.py
3. Open the OVL files of any creature and Unpack into a folder.
4. Inject the diffuse file.
5. An Error appears: "not enough values to unpack (expected 2, got 1)"

**Expected behavior**
Injecting a Diffuse File should work. Although, curiously Normals and Blendweights work fine. Furthermore, Normal Maps can be injected individually without having the need to select all of them.

**Screenshots**
[Screenshot 1](https://cdn.discordapp.com/attachments/330199256122130432/920124566779613214/unknown.png)
[Screenshot 2](https://cdn.discordapp.com/attachments/330199256122130432/920124982997168239/unknown.png)
**Version Info:**
 - Python Version: 3.9.1
 - Blender Version: 2.93.5
 - Cobra Tools Version Master, date 12/13/2021]
 
 **Log Files:**
 - Close the tools and attach the appropriate log file here. [e.g. cobra-tools/ovl_tool_gui.log]
[ovl_tool_gui.log](https://github.com/OpenNaja/cobra-tools/files/7707967/ovl_tool_gui.log)

**More Information**

An older version of Cobra Tools Master works when it comes to injecting textures. I do not know the exact number but the date I downloaded it was on 11/22. If you need more information or tell me if I did the report incorrectly, let me know ^^.

**Comment by HENDRIX-ZT2** [comment]
Confirmed, thanks for the thorough report!

**Comment by HENDRIX-ZT2** [comment]
Fixed in current master!
