### ISSUE TITLE
permission denied error

### ISSUE THREAD

**Issue by akbartalpur19** [OpenNaja/cobra-tools#158]
im using the lastest version of the addon and blender and when i try to import this happenes
![Screenshot (177)](https://user-images.githubusercontent.com/89235972/147014167-3f51fb48-52f4-4667-978f-345548e47a4b.png)
![Screenshot (193)](https://user-images.githubusercontent.com/89235972/147014243-13fcd53d-a748-4728-ba80-405aeb4388d5.png)
how to fix please help me

**Comment by HENDRIX-ZT2** [comment]
Closed for duplicate. Non-issue. Your fault.

**Comment by akbartalpur19** [comment]
bruh it didn't help the program still thinks it's in program files even if I moved it to  other addons folder

**Comment by akbartalpur19** [comment]
> Closed for duplicate. Non-issue. Your fault.
bruh it didn't help the program still thinks it's in program files even if I moved it to  other addons folder
