### ISSUE TITLE
.mdl2s not importing

### ISSUE THREAD

**Issue by Shuwnn** [OpenNaja/cobra-tools#159]
Forgive me if there's an easy fix for this, I just recently started trying to mod Planet Zoo. What should I do if I installed the newest plugin, but when I try to import any animal model into Blender it simply doesn't open? I can see the file but it never opens. No error ever shows either.

**Comment by HENDRIX-ZT2** [comment]
Make sure you use the current master for both the plugin and to extract mdl2 files. Extract them afresh and try again.
