### ISSUE TITLE
.TEX injection not working properly

### ISSUE THREAD

**Issue by LordOfPizza** [OpenNaja/cobra-tools#166]
Can't replace tex files in OVL, causes other texture files to disappear when unpacking & makes game crash

**Comment by HENDRIX-ZT2** [comment]
Injecting tex is not allowed at the moment. Inject PNGs instead. Tex is only useful for creating or adding new files.
Current master?

**Comment by LordOfPizza** [comment]
> Injecting tex is not allowed at the moment. Inject PNGs instead. Tex is only useful for creating or adding new files. Current master?

Using the latest master, trying to inject 2K textures for JWE2. It was mentioned on discord but I suppose it doesn't work yet

**Comment by HENDRIX-ZT2** [comment]
Due to unknown problems with JWE2, this only works for PZ for now.

**Comment by LordOfPizza** [comment]
Ah I see, thanks for the heads up
