### ISSUE TITLE
Anim/Banim import menus sense?

### ISSUE THREAD

**Issue by fobetor** [OpenNaja/cobra-tools#169]
Hi
Just wondering... OR I am doing something wrong with blender and Jurassic park and Planet zoo or why does blender has the import options of animations if they are not supported/implemented? (Is what I have been able to read in the issues within this github)
As I am not an expert... how can I make a bani or what is the difference between a manis and banis?
thanks in advance

**Comment by HENDRIX-ZT2** [comment]
You can not 'make' them, only edit the files in a hex editor. The import plugins are not too useful. Bani import somewhat works for some banis, not all. Manis does not work at all.

**Comment by fobetor** [comment]
thanks
and… a clue about that HEX editing procedure?


Fernando J Sanchez Menendez

**Comment by HENDRIX-ZT2** [comment]
Edit byte by byte and observe the changes you get ingame 😄
