### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by jacobm170** [OpenNaja/cobra-tools#170]
when i try to export certain dinosaures the .mdl2 doesnt extract what could be the issue

**Comment by HENDRIX-ZT2** [comment]
Upgrade tools, upgrade plugin, extract again, try again, supply log file.

**Comment by fadingsignal** [comment]
I just installed the latest tools fresh for the first time and am unable to extract any .mdl2 files either

![mdl2](https://user-images.githubusercontent.com/13229928/153692285-092aad8f-5ce1-4956-b033-77c4dd6b7def.jpg)

**Comment by HENDRIX-ZT2** [comment]
Updated instructions on the wiki. MS2 is the relevant file type now.
