### ISSUE TITLE
Can't unpack mdl2 files

### ISSUE THREAD

**Issue by ShadowGaster** [OpenNaja/cobra-tools#175]
For some reason I can't extract any mdl2 files from any game, jwe 1&2, planet zoo, etc. Whenever I try the files are greyed out and unable to be extracted 
![Leo](https://user-images.githubusercontent.com/100167440/155030320-17fedd86-012b-451c-9bba-1ca1eab903b4.png)

**Comment by ShadowGaster** [comment]
Nvm... I'm an idiot, My bad everyone

**Comment by HENDRIX-ZT2** [comment]
Extract ms2, not mdl2.

**Comment by ShadowGaster** [comment]
> Extract ms2, not mdl2.

Well I did that now thank you, But it's only the harness not the actual dinosaur
