### ISSUE TITLE
Model not being extracted?

### ISSUE THREAD

**Issue by ShadowGaster** [OpenNaja/cobra-tools#176]
So when i was importing the ms2 from the extracted liopleurodon I was only presented with the airliftstraps.

Did I mess up with the cobra tools or is there a glitch?

Here's the imported "model" idk if it helps 
![unknown](https://user-images.githubusercontent.com/100167440/155260135-33c91df9-5b8f-452b-8bf3-89f648b50652.png)

**Comment by HENDRIX-ZT2** [comment]
It's supposed to be like that. Switch the scene.
