### ISSUE TITLE
blender plugin import ms2 model to bone only

### ISSUE THREAD

**Issue by sinhphan** [OpenNaja/cobra-tools#177]
**Describe the bug**
blender plugin import ms2 model to bone only

**Screenshots**
![image](https://user-images.githubusercontent.com/1941392/158394817-d36c3538-380c-45b2-983f-c3029512fe8f.png)

**Version Info:**
 - Python Version: 3.7.6
 - Blender Version: 2.93
 - Cobra Tools Version master, date downloaded 15/03/2022
 
 **Log Files:**
[ovl_tool_gui.log](https://github.com/OpenNaja/cobra-tools/files/8254052/ovl_tool_gui.log)

**Comment by HENDRIX-ZT2** [comment]
Change the scene, top right corner.
