### ISSUE TITLE
OVL - Inject non-square images

### ISSUE THREAD

**Issue by HENDRIX-ZT2** [OpenNaja/cobra-tools#18]
Mip packing needs to be debugged, ends up wrong by a few bytes.

**Comment by HENDRIX-ZT2** [comment]
Still valid, eg. for dinosaurs_sizelarge_nasutoceratops.tex

**Comment by HENDRIX-ZT2** [comment]
Make use of Tex MIPS info to pull apart the MIPS and pad them as needed

**Comment by ilodev** [comment]
Sorry @jacobm170 this is not the right place to ask a question as specific as that one being as off-topic in this bug threat. Please join the modding discord for modding help in general https://discord.gg/myQkG8Q
