### ISSUE TITLE
OVL - Unpacking .bnk files Attribute Error

### ISSUE THREAD

**Issue by clang-1859** [OpenNaja/cobra-tools#183]
Attribute error when trying to unpack an ovl containing .bnk files during a check for user_version.is_jwe.
![image](https://user-images.githubusercontent.com/48227342/163657521-985a119a-6b90-4413-ad3e-b1b0462eb772.png)

Error trying to unpack a Planet Zoo ovl, but it looks like the check would probably fail for any game?

**Comment by HENDRIX-ZT2** [comment]
Unpacking tested for JWE1, JWE2, PZ. Works for both s and b bnks.
