### ISSUE TITLE
DLL load failed while importing QtWidgets: The specified module could not be found.

### ISSUE THREAD

**Issue by CyberDudee** [OpenNaja/cobra-tools#184]
When I try to open ovl_tool_gui.py, i get the following error:

Traceback (most recent call last):
  File "C:\Users\(myusername)\Desktop\cobratools\ovl_tool_gui.py", line 11, in <module>
    from PyQt5 import QtWidgets, QtGui, QtCore
ImportError: DLL load failed while importing QtWidgets: The specified module could not be found. 

Does anybody have a fix for this? I dont know much about python and I want to edit JWE2 OVLs

**Comment by CyberDudee** [comment]
By the way I installed QtWidgets using Anaconda python

"pip install qtwidgets" is the command I used

**Comment by HENDRIX-ZT2** [comment]
Probably your python version is too new. Use 3.7. Don't use anaconda if possible.

**Comment by CyberDudee** [comment]
Thank you
