### ISSUE TITLE
Extracting Content0 Main.ovl causes an error

### ISSUE THREAD

**Issue by elucca** [OpenNaja/cobra-tools#19]
Attempting to open Main.ovl from the Content0 folder causes an unspecified error which prevents the file from being successfully opened. No error is displayed in the console. Usually but perhaps not always this happens in the "Mapping pointers" stage. All other ovl files I've tried open fine.

![error](https://user-images.githubusercontent.com/32358066/71142866-5a271f80-2221-11ea-8400-eb2bbaa7937a.png)

Version: 1.3.0 release

I don't know if this error happens on just my machine. Two problems I've ruled out: I'm not running out of RAM, and my ovl file is not corrupt (redownloaded it from Steam just to be sure).

**Comment by HENDRIX-ZT2** [comment]
That's weird. I'll investigate and try to replicate your error.

**Comment by HENDRIX-ZT2** [comment]
I noticed that there's almost a million frag entries in the file so this is probably an optimization issue.

**Comment by elucca** [comment]
I tried extracting this file on my Ubuntu machine, and it works fine there. I don't know that it's OS-related though. I'll do some more experimenting to see if it's maybe a Python version thing or something.

**Comment by HENDRIX-ZT2** [comment]
This is actually due to using 32bit version of python.
