### ISSUE TITLE
OVL - support JWE2 tex create

### ISSUE THREAD

**Issue by july702** [OpenNaja/cobra-tools#195]
**Continuing.. #194**  
Thank [HENDRIX-ZT2] for fixing error #194 . I continued to test and found 1 more error. Hope you see. Thank you

Describe the bug
Step 1: I have successfully unpacked an ovl file and changed the colors of texture, I still keep the png format and the old name.
Step 2: I re-inject the .ovl file and save new .ovl. And when I unpack the new ovl to check, the texture is still the same, nothing has changed.
I found error: WARNING | Unsupported file type:
To Reproduce
1.Go to the Cobra Tools Master Folder
2.Click on ovl_tool_gui.py
3.Open the OVL files of any creature.
4. Unpack into a folder.
5. Inject the diffuse file.
7. An Error appears: WARNING | Unsupported file type: tyrannosaurusrex.pbasediffusetexture.png (in my case, i tried inject new texture of Rex JWE)
8. Save and Check new ovl: not have new texture.
Expected behavior
Fix error
![2022-05-08_11h23_40](https://user-images.githubusercontent.com/24586204/167281989-e79f7a86-520f-4530-a8fc-0b7ef365226d.png)
Version Info:
INFO | Running python 3.7.9 (tags/v3.7.9:13c94747c7, Aug 17 2020, 18:58:18) [MSC v.1900 64 bit (AMD64)]
INFO | Running cobra-tools 2.3.8, https://github.com/OpenNaja/cobra-tools/commit/046f2fd5b80aa8479803ebd2de1031df0e62b11a - Sat May 7 22:45:05 2022 +0200
Log Files:
[ovl_tool_gui.log](https://github.com/OpenNaja/cobra-tools/files/8646346/ovl_tool_gui.log)

[Log from test.bat.txt](https://github.com/OpenNaja/cobra-tools/files/8646347/Log.from.test.bat.txt)

[Log from cmd when running cobra tool.txt](https://github.com/OpenNaja/cobra-tools/files/8646348/Log.from.cmd.when.running.cobra.tool.txt)

**Comment by HENDRIX-ZT2** [comment]
You need to inject the Tex file instead of the PNG. The Tex file must be located in the same spot as the PNG so it can then load the required pngs automatically.

**Comment by StrikeHead123** [comment]
I have the same problem as well, but i cant inject the tex file because its not one of the supported files that i can inject to the ovl

**Comment by HENDRIX-ZT2** [comment]
Adding new tex files works in PZ with current master. Test if you can do so for JWE1/2.

**Comment by HENDRIX-ZT2** [comment]
JWE2 has 16 bytes per texstream root, with an uint64 for lod index

**Comment by HENDRIX-ZT2** [comment]
Fixed!
