### ISSUE TITLE
Cannot Inject Models

### ISSUE THREAD

**Issue by LeafProductions** [OpenNaja/cobra-tools#196]
Extracted Dingo Model from Clean Dingo OVL

Edited Model

Generated Fur

Injected into Ovl

Loaded game, placed animal in habitat 

Crash

**Comment by HENDRIX-ZT2** [comment]
Current master? MS2 injection is broken for some reason, but you can safely delete the original MS2, then add your edited MS2 back in.

**Comment by HENDRIX-ZT2** [comment]
Fixed by deleting & readding internally.
