### ISSUE TITLE
Make reverse sets obsolete

### ISSUE THREAD

**Issue by HENDRIX-ZT2** [OpenNaja/cobra-tools#2]
Can probably use fragment addresses to solve the mapping problem.

**Comment by HENDRIX-ZT2** [comment]
Funnily most dino base meshes load properly regardless of reverse sets after the latest refactoring pass. Airliftstraps don't, so this needs to be investigated still.

**Comment by harlequinzeg0** [comment]
Recent Updates have heavily refactored the frag grabbing, matcol style pointers fixed this issue
