### ISSUE TITLE
Matcol for Indom has odd padding

### ISSUE THREAD

**Issue by harlequinzeg0** [OpenNaja/cobra-tools#20]
m1_d0 = struct.unpack("<8I", m1.pointers[0].data)
m1_info_count = m1_d0[2]

expected 16 bytes of data, got 24 bytes instead on last attribute count frag in the list.

**Comment by harlequinzeg0** [comment]
Solution is known, just adding for reference

**Comment by HENDRIX-ZT2** [comment]
Solution implemented, needs ingame testing.

**Comment by HENDRIX-ZT2** [comment]
Working, closed.
