### ISSUE TITLE
ERROR: 'OVLFile' Object has no attribute 'Pools'

### ISSUE THREAD

**Issue by Aron2988** [OpenNaja/cobra-tools#201]
After installing Cobra Tools Version: bf996ab6 I can no longer open or unpack any Dinosaur OVL's for J.W.E 2

Using: 

Python Version 3.7.9-amd64

[Microsoft Visual C++ Redistributable 2017 x64

[Microsoft Visual C++ Redistributable 2013 x86

![image](https://user-images.githubusercontent.com/106612521/171221322-e50ed4b9-0056-47cd-9a96-1debb1b35d63.png)

![image](https://user-images.githubusercontent.com/106612521/171222386-1af6b137-8334-4f6c-a11f-59438600df09.png)
****

![image](https://user-images.githubusercontent.com/106612521/171222636-1b328be0-48ab-4bc3-a47f-8e669bbcbff7.png)

**Comment by HENDRIX-ZT2** [comment]
Use current master
