### ISSUE TITLE
The .ms2 model in blender only show skeleton 

### ISSUE THREAD

**Issue by Dejavu0709** [OpenNaja/cobra-tools#202]
Hi, I try to use Cobra™ Tools for Blender, but i could not get the expected result.
 Jurassic World Evolution2
1. double click tovl_tool_gui.py
2. open a dinosaur ovl  file
3. unpack to get the .ms2 model file
4. blender 2.9,2, import the .ms2 file

![image](https://user-images.githubusercontent.com/71498147/171602498-dbb6b06e-67c7-4a1e-8587-8d9401b911c2.png)
why only show skeleton of the model, am I operating with the worng steps?

**Comment by HENDRIX-ZT2** [comment]
Change the scene in blender to the dino model.

**Comment by Dejavu0709** [comment]
> 
the same with you，have you solved it？It is confusing me for a long time

**Comment by Dejavu0709** [comment]
> '1 file errored and were not extracted'

thank you for the reply，I think it is because of  load ovl and unpack it with errors，here  is the error shortcut ：

![1654485774(1)](https://user-images.githubusercontent.com/71498147/172089721-e1d0cff9-df59-42c9-b9ae-968c7da5386e.png)
![1654485956(1)](https://user-images.githubusercontent.com/71498147/172089730-613ccc72-424f-4ff9-9110-2e1ba985d583.png)

**Comment by Dejavu0709** [comment]
> Change the scene in blender to the dino model.

I get it, Thanks very much

**Comment by Dejavu0709** [comment]
> I'm having this issue as well, when I unpack it says '1 file errored and were not extracted' then when importing it into Blender (newest version as of 6/3/22) it only displays the airlift straps and bones



> I'm having this issue as well, when I unpack it says '1 file errored and were not extracted' then when importing it into Blender (newest version as of 6/3/22) it only displays the airlift straps and bones
Change the scene in blender，get it ！
![image](https://user-images.githubusercontent.com/71498147/172095657-ab7deee2-4c8a-40dc-adbd-f7f113cfafa3.png)
