### ISSUE TITLE
GUI improvements

### ISSUE THREAD

**Issue by HENDRIX-ZT2** [OpenNaja/cobra-tools#203]
Generic issue to track and collect ideas for GUI improvements:
- worker thread
- ~accept OVL drops on whole GUI~
- properly store settings & presets

**Comment by HENDRIX-ZT2** [comment]
- only_types tuple file extensions are case sensitive so ('.FGM', '.TEX', '.MS2') won't work.  Extensions might be case sensitive elsewhere too
- with show_temp_files=False I'm getting DDS in my extract directory whereas when dragging the files from the GUI you get no DDS.  I guess because for the GUI you are extracting to temp and then moving the non-temp files.  So then what is show_temp_files really doing, does it remove it from out_paths and then I have to manually delete the files not in out_paths?

**Comment by hexabits** [comment]
- Rename/Rename Contents on Selected

**Comment by hexabits** [comment]
Crash when Ctrl-A and then use Filter.

**Comment by HENDRIX-ZT2** [comment]
> Crash when Ctrl-A and then use Filter. Edit: Hangs, technically.
> 
> Use case: Wanted to Select All, use Filter then de-select the filtered items, then delete all.

I don't have this issue, or I'm doing something differently. May have been fixed by [cbd7de0](https://github.com/OpenNaja/cobra-tools/commit/cbd7de0ec91cbde4060bdc6698d7952131b8892f)
1. Type filter
2. Select all
3. (Clear filter, only the selected files remain selected)
4. Delete selected

**Comment by hexabits** [comment]
> > Crash when Ctrl-A and then use Filter. Edit: Hangs, technically.
> > Use case: Wanted to Select All, use Filter then de-select the filtered items, then delete all.
> 
> I don't have this issue, or I'm doing something differently. May have been fixed by [cbd7de0](https://github.com/OpenNaja/cobra-tools/commit/cbd7de0ec91cbde4060bdc6698d7952131b8892f)
> 
> 1. Type filter
> 2. Select all
> 3. (Clear filter, only the selected files remain selected)
> 4. Delete selected

For example: 

1. Open Content0/AssetPackagesExtrasList.ovl
2. Ctrl-A
3. Start typing in Filter

It just hangs seemingly forever.   The smaller OVLs don't.   Content0/Main takes quite a while to filter but does.  It's probably some exponential explosion in time to do the Filter for some reason.   But it does not take anywhere near as long without Ctrl-A.

Anyway the use case can't be done anyway, when you filter stuff, the items get deselected.  So there is no way to delete everything not matching a substring.

**Comment by HENDRIX-ZT2** [comment]
Threading is also implemented for OVL loading
