### ISSUE TITLE
config.ini missing or broken

### ISSUE THREAD

**Issue by Ahnuro62** [OpenNaja/cobra-tools#204]
Hey Guys.

after searching for some hours for a solution i gave up.
in the ovl_tool_gui i manage to unpack but i get some errors 

"2 files have errored and were not extracted."

i have this problem on my new PC.
I cant remember anymore what i did on my old PC, but it worked perfectly befor.

all requirements are installed aswell.

i found this later 

INFO | Running python 3.10.5 (tags/v3.10.5:f377153, Jun  6 2022, 16:14:13) [MSC v.1929 64 bit (AMD64)]
INFO | Running cobra-tools 2.4.0, 346d6ef6 - Fri Jun 10 17:24:49 2022 +0200
config.ini is missing or broken!
INFO | Loading hash table...
INFO | Loaded 641003 hash - name pairs in 0.59 seconds

i hope you can help me and give me an instruction to fix it.
i'm to dumb for this right now :D

i think this is the problem that i need to fix.

**Comment by HENDRIX-ZT2** [comment]
non-issue, it is created once you restart the tools.
