### ISSUE TITLE
FILES NOT EXTRACTED DUE TO ERROR

### ISSUE THREAD

**Issue by runecapes** [OpenNaja/cobra-tools#209]
been trying to unpack ms2 files so i can use them in blender but they will always fall under the files not extracted due to error. doesnt even explain what the error is? any fixes to this?

**Comment by HENDRIX-ZT2** [comment]
JWE2? Check the Biosyn toggle before opening the ovl

**Comment by runecapes** [comment]
im not using the biosyn stuff tho i just want some vegetation

**Comment by HENDRIX-ZT2** [comment]
your game is the biosyn update though? The version name is a little misleading

**Comment by runecapes** [comment]
oh ok i did it and the vegetation in blender is just a bunch of parts and stuff and its confusing let me send image

**Comment by runecapes** [comment]
https://prnt.sc/XRFMTSN_4LLQ

**Comment by runecapes** [comment]
do you know why it looks like this

**Comment by HENDRIX-ZT2** [comment]
Need to update your blender plugin too.

**Comment by runecapes** [comment]
wdym need to update the blender plugin? i got the latest release and stuff

**Comment by HENDRIX-ZT2** [comment]
You need master, releases don't have the latest JWE2 fixes. They completely changed their file format.

**Comment by runecapes** [comment]
can you send me a link? i cant find it and how do i disable this other cobra blender tool

**Comment by HENDRIX-ZT2** [comment]
Delete it from the blender addons folder. Can also try to update to master from the addon preferences.
Direct link to master:
https://github.com/OpenNaja/cobra-tools/archive/refs/heads/master.zip

**Comment by runecapes** [comment]
how do i delete it from the blenders addons

**Comment by runecapes** [comment]
nvm, im using master version and same thing is happening

**Comment by HENDRIX-ZT2** [comment]
In that case, upload the OVL + OVS file to investigate.

**Comment by runecapes** [comment]
whats the OVS file

**Comment by runecapes** [comment]
https://www.mediafire.com/file/nrhdm3nq8y2oo9f/Tree_Pine.ovl/file here is OVL file

**Comment by runecapes** [comment]
i dont know what an OVS file is

**Comment by HENDRIX-ZT2** [comment]
> i dont know what an OVS file is

Would be in the same spot if it exists, but not all things have an OVS.

**Comment by runecapes** [comment]
no it doesnt have the OVS file just OVL

**Comment by runecapes** [comment]
thank you for helping btw

**Comment by runecapes** [comment]
have you found a solution to this?

**Comment by runecapes** [comment]
ive also been trying to find the problem but cant find crap

**Comment by HENDRIX-ZT2** [comment]
Confirmed, does not load properly into blender.

**Comment by HENDRIX-ZT2** [comment]
Implemented this new model format. Imports into blender now:
![grafik](https://user-images.githubusercontent.com/28632661/175815559-3dcf6f94-f9ba-446d-8644-6133a52d1dd5.png)
