### ISSUE TITLE
extracting .ms2 files of vegetation glitches it out 

### ISSUE THREAD

**Issue by runecapes** [OpenNaja/cobra-tools#210]
how do i fix this?

heres an image
![this ism y debug i need help (i need help](https://user-images.githubusercontent.com/108169744/175764649-e65ef0a7-ae4e-44fe-8e17-89203f8d243e.png)
:

**Comment by runecapes** [comment]
this is jwe2

**Comment by HENDRIX-ZT2** [comment]
Duplicate. Don't raise separate issues.
