### ISSUE TITLE
JWE stuck on launch after injecting ovl files

### ISSUE THREAD

**Issue by coaco23** [OpenNaja/cobra-tools#211]
**OVL files cannot be opened ValueError after injecting files**
I injected files into ovl using ovl_tool_gui.py, I saved the ovl file and launch the jurassic world evolution game but it stuck in the launch screen. Then I tried to open the ovl file I've injected before and this came up

![gambar](https://user-images.githubusercontent.com/108212025/175803390-00fc2c00-f4b1-492d-8dd2-45e44d2acc9d.png)

**NEED HELP**

**Version Info:**
 - Python Version: [3.10.0]
 - Cobra Tools Version [master 2.4.0]
 
 **Log Files:**
 - 
[ovl_tool_gui.log](https://github.com/OpenNaja/cobra-tools/files/8986114/ovl_tool_gui.log)

**Comment by HENDRIX-ZT2** [comment]
Please supply the ovl file.

**Comment by coaco23** [comment]
[Main ovl.zip](https://github.com/OpenNaja/cobra-tools/files/8986778/Main.ovl.zip)
It's a Main.ovl from Content0 which I injected with c0path.fdb

**Comment by HENDRIX-ZT2** [comment]
This is the file you have modified. I would need to stock, unedited version.

**Comment by coaco23** [comment]
[Main.zip](https://github.com/OpenNaja/cobra-tools/files/8986818/Main.zip)
Oh, here it is

**Comment by HENDRIX-ZT2** [comment]
For now current master does not support editing JWE1. Some changes need to be made to the naming and buffer code to allow for that again.

Meanwhile this old release should work: https://github.com/OpenNaja/cobra-tools/releases/tag/2.3.8

**Comment by coaco23** [comment]
Work like a charm. Thank you
