### ISSUE TITLE
cobra tools format problem

### ISSUE THREAD

**Issue by Lildatel** [OpenNaja/cobra-tools#214]
hello, I have a problem with cobra tools, I installed everything for editing skins, but when injecting the edited file through cobra tools back into the OVL file, it is not PNG between supported formats, all people witch have the video tutorials have PNG, can you please give me some advice? I've been trying for a week and I can't seem to get it right. I will be very grateful for your reply. Have a nice day
Python version  -          3.10.5
Cobra tools version-    2.4.0  
Formats wich cobra tools support for injecting to OVL file: *animalresearchstartunlockedsettings*assetpkg*bani*banis*bnk*cinematic*curve*tex*texturestream*enumnamer*fct*fdb*fgm*gfx*guesteconomy*climbproofdata*habitatboundarydata*habitatboundaryprop*island*janitorsettings*dinosaurmaterialeffects*dinosaurmaterialpatterns*dinosaurmaterialvariants*mechanicresearchsettings*mergedetails*motiongraphhvars*mdl2*model2stream*ms2*posedriverdef*pscollection*renderparametercurves*renderparameters*restaurantsettings*ridesettings*txt*uimoviedefinition*userinterfaceicondata*voxelskirt*wmetasb*world*wsm*xmlconfig

**Comment by HENDRIX-ZT2** [comment]
Tutorials are outdated, you need to inject the .tex file, which will automatically find the corresponding .png file.

**Comment by Lildatel** [comment]
thank you very much man
