### ISSUE TITLE
Unable to inject PNG files in cobra master tools. How to fix it. Becase PNG format is not supported?

### ISSUE THREAD

**Issue by SMBSGamerTamil** [OpenNaja/cobra-tools#215]
I am trying to change a dinosaur colour in JWE2 game. Using the Cobra Master tool, I unpacked one of the dinosaur from the game and changed the dinosaur colour in PNG base file. But when I try to inject the file, PNG is not supported during inject. Please assist how to fix this issue.

**Comment by HENDRIX-ZT2** [comment]
Duplicate of #214
Closed
