### ISSUE TITLE
Scrolling the scroll wheel while hovering a value edits it even if the value is unselected in the FGM editor

### ISSUE THREAD

**Issue by SleepyEngi** [OpenNaja/cobra-tools#22]
Utilizing the scroll wheel to scroll causes problems because you can accidentally edit a value while attempting to scroll down the list of values. If the scroll wheel is restricted to only editing values when the value is selected, it would be easier to scroll down without having to use the scroll bar

**Comment by HENDRIX-ZT2** [comment]
That is standard Qt behavior. You can scroll over the attribute names instead, those won't change.

Possible fixes:
https://stackoverflow.com/questions/3241830/qt-how-to-disable-mouse-scrolling-of-qcombobox/43467364
https://stackoverflow.com/questions/5821802/qspinbox-inside-a-qscrollarea-how-to-prevent-spin-box-from-stealing-focus-when
