### ISSUE TITLE
OVL - Saving crashes JWE1 (after modifying skin)

### ISSUE THREAD

**Issue by SMBSGamerTamil** [OpenNaja/cobra-tools#222]
Hi Support team,

I am playing Jurassic world evolution game and I unpacked and modified the PNG file with new skin color and injected TEX file in Cobra master tools and saved the OVL file as well. I used the same procedure how I do it for JWE2. JWE 1 game is not loading and throwing error after added the new OVL file. I followed the same procedure in JWE2 and it is working well. Only JWE1 is having problem. Could you please guide me.

Thanks,

**Comment by HENDRIX-ZT2** [comment]
You can not use current tools for JWE1.

**Comment by HENDRIX-ZT2** [comment]
The buffer logic needs to support the correct sorting algorithm.

**Comment by HENDRIX-ZT2** [comment]
Dupe of #211

**Comment by SMBSGamerTamil** [comment]
Thanks for your support
