### ISSUE TITLE
#211 - Unable to enable this add on

### ISSUE THREAD

**Issue by SMBSGamerTamil** [OpenNaja/cobra-tools#223]
Hi Support team
As per the suggestion from ticket number #211, I have installed cobra-tools-2.3.8 and tried to enable it into blender. However, I am unable to enable it and throwing some error. Could you please help me resolve this issue?

![image](https://user-images.githubusercontent.com/108780144/182014347-db6851c5-a178-4b50-a478-d97a88fd0009.png)

![image](https://user-images.githubusercontent.com/108780144/182014385-b3e3b3ea-57f6-4532-a3ff-ff1db47a412c.png)

Thanks

**Comment by HENDRIX-ZT2** [comment]
Blender does not like the naming with 2.3.8, so rename the zip and the folder inside before installing it.
