### ISSUE TITLE
Cobra tool MS2 "exporting error "

### ISSUE THREAD

**Issue by SMBSGamerTamil** [OpenNaja/cobra-tools#225]
Hi Team,

Need help. I imported a dinosaur from Jurassic world evolution 2 game into blender using Cobra master tool plugin. I have made small sculpting on the dinosaur. After that, I tried to export the MS2 file, it is showing the error as "Set the pack base value for scene "xxxxxx". could you please help me to resolve this issue?

![image](https://user-images.githubusercontent.com/108780144/182203298-4285f782-61f4-402a-b43e-24b6bae19e59.png)

**Comment by HENDRIX-ZT2** [comment]
You can't export JWE2 meshes as they have changed the ms2 format. Wait while we re-implement it.

**Comment by SMBSGamerTamil** [comment]
Thanks
