### ISSUE TITLE
FGM Editor purpose: psublayer0diffuseTint 

### ISSUE THREAD

**Issue by Nyymeria-11** [OpenNaja/cobra-tools#23]
Attribute is found in Rocks_Ice.ovl, rocks_01_mat.fgm. 
Attribute is "psublayer0diffuseTint" followed by 3 number values which correspond to RGB in a 0-1 scale.  It tints the diffuse texture to whatever rgb you input. Used it to make the notoriously blue ice rocks white. Tooltip could read "Tints the indicated diffuse layer to the specified rgb value".

![Screenshot (54)](https://user-images.githubusercontent.com/59132394/71318056-82449780-2448-11ea-8e86-1e650f5c23ba.png)
![Screenshot (55)](https://user-images.githubusercontent.com/59132394/71318057-82449780-2448-11ea-9f68-c95ec89d07b0.png)

**Comment by HENDRIX-ZT2** [comment]
Thank you very much, well done!

**Comment by HENDRIX-ZT2** [comment]
Added to tooltips
