### ISSUE TITLE
JWE1 There was a problem after injecting the MS2 file 

### ISSUE THREAD

**Issue by 2239614634plr** [OpenNaja/cobra-tools#235]
Only when I zoom in can I see the changed Dinosaur model.If I zoom out, I just can see the Dinosaur model before the change.
cobra-tools 2.3.7/2.3.8   Blender3.0.0

**Comment by 2239614634plr** [comment]
Hi please help me.

**Comment by HENDRIX-ZT2** [comment]
You need to generate lods before exporting.

**Comment by 2239614634plr** [comment]
> 
![CBLWJF(I$}RZ@$4U@2@_TW](https://user-images.githubusercontent.com/111658859/185954840-972ae161-4f8b-4701-a7fb-15e5d4fe8f13.png)

I'm sorry for my stupidity. But I can‘t find it

**Comment by 2239614634plr** [comment]
> 您需要在导出之前生成 lod。
I clicked Create Fins. But this does not work

**Comment by HENDRIX-ZT2** [comment]
Your plugin is not up to date so it misses the lod button.

**Comment by 2239614634plr** [comment]
> Your plugin is not up to date so it misses the lod button.

But the 2.4.0 can't be used for jwe1

**Comment by 2239614634plr** [comment]
> Your plugin is not up to date so it misses the lod button.

#211

**Comment by HENDRIX-ZT2** [comment]
JWE1 should work fine now with current master.
