### ISSUE TITLE
Replace a empty material in blender with a new imported fgm data

### ISSUE THREAD

**Issue by ilodev** [OpenNaja/cobra-tools#246]
Currently after importing a model, the plugin creates empty materials for it (if it can't find the fgm files).

We have the option to import materials later on, but the import (having the same name as the already created ones) is not replacing the existing materials but creating new ones.

It would be good to have the option to replace an empty material instead.

**Comment by HENDRIX-ZT2** [comment]
Now I finally get what you mean. Throw away the old data block of the same name and replace it.

**Comment by ilodev** [comment]
yeah but now i have the knowledge to do it myself, and I have a few more
plans involving materials

**Comment by HENDRIX-ZT2** [comment]
You'll notice I've refactored material import. We can improve it some more so we are able to take per-shader variations for the uses of the different channels of textures with the same suffix.

**Comment by ilodev** [comment]
I modified the plugin on mateiral creation just to double check material by name with lowercase. Blender does support mateirals with diff name capitalization, however we lose this in the ovl since all files are lowercase and this was failing on import.,

**Comment by ilodev** [comment]
alright, pushed this change, alongside other QoL to search for materials in the user libraries when importing an ms2, no more needing to have the fgms in the same folder if the user has created a material library first (will document that).
