### ISSUE TITLE
Unable to export Dinosaur from Blender to the game

### ISSUE THREAD

**Issue by SMBSGamerTamil** [OpenNaja/cobra-tools#247]
Hi Team,
I have done a small sculpting on T Rex and tried to export this to game. When I try to export this, I am still getting the below error. However, I have seen many of the modders already started to sculpt the dinosaurs after the Biosyn expansion. Please guide me how to export this to game from Blender

![image](https://user-images.githubusercontent.com/108780144/190998732-0a6079c7-7a53-48e5-8b1e-13020b1782d4.png)

The error is "Set the pack base value for the scene "Tyrannosaurusrex93".

**Comment by HENDRIX-ZT2** [comment]
Re-import with current tools, start over.
