### ISSUE TITLE
FGM Editor experimentation findings

### ISSUE THREAD

**Issue by SleepyEngi** [OpenNaja/cobra-tools#25]
Here's what I've found so far from changing values in the FGM editor

AlphaTestRef: The higher this value, the faster transparent materials will fade into becoming invisible as you move away from them.

gWetBrightness: The higher this value, the brighter the diffuse texture becomes when the animal is wet.

pDirtDryColour: RGB values divided by 1000 that slightly affect the color when the animals are muddy
pDirtWetColour: RGB values divided by 1000 that slightly affect the color when the animals are wet

pRenderLayersOveride: I saw no visible changes when changing this value. 

pTransmittance: normally 0, a value of 1 makes light go through the object so shadows are removed, but the object remains opaque. 

pWetSpecularStrength: Makes the model more reflective while wet independently of the blue value of the roughnesspacked texture

pMaximumSnowAmount: No visible change. 
![fgm findings](https://user-images.githubusercontent.com/59126707/71500382-60715900-282a-11ea-9146-721ba6335b5a.png)

**Comment by HENDRIX-ZT2** [comment]
Thanks a lot, good work!

**Comment by HENDRIX-ZT2** [comment]
Added to tooltips
