### ISSUE TITLE
Problem with injection of modified file

### ISSUE THREAD

**Issue by Alex23344545** [OpenNaja/cobra-tools#251]
Hello, when I inject a Alberto modified mdl2 file into the Alberto ovl file via cobra tool, I have this error message: No match for <Mdl2Holder: albertosaurus_airliftstraps.mdl2 [OVL], V6, T6, M6, L0>

I can send the modified mdl2 file if someone want.

**Comment by HENDRIX-ZT2** [comment]
Outdated tools.
