### ISSUE TITLE
Juvenile Indian Elephant OVL saved successfully; crashes Planet Zoo upon loading save file immediately. 

### ISSUE THREAD

**Issue by SleepyEngi** [OpenNaja/cobra-tools#26]
Tested both after editing a texture and saving, and not editing anything and saving. The game crashes upon loading any save file. No errors were shown during the saving process of the OVL. 

Notes: 
-Other juvenile models did work upon saving with or without edits. 
-The juvenile model for the indian elephant has fur shaders, unlike the adult versions of itself.
-The unpacked files for the juvenile indian elephant included files that no other furry animals include when unpacked, an opacity texture for the fins, and a diffuse texture for the fins. Animals like the juvenile gray wolf and the grizzly bear did not have any of these textures despite having fur shaders. 
-upon using a backup of the original juvenile indian elephant OVL, the save file loads correctly. But just opening it with the OVL editor, and saving it, causes the game to crash upon loading. Even without changing anything.

**Comment by HENDRIX-ZT2** [comment]
No longers seems to be an issue with current dev version, all dats and ovl data match, needs to be verified ingame.

**Comment by HENDRIX-ZT2** [comment]
Fixed, closed.
