### ISSUE TITLE
Empty OVL creation bug

### ISSUE THREAD

**Issue by ilodev** [OpenNaja/cobra-tools#260]
**Describe the bug**
OVL without content does not create STATIC ovs section in some cases.

**To Reproduce**
1. Open OVL tool
2. open Jurassic World Evolution 2\Win64\ovldata\Content_VoiceOver\Audio\English(US)\Audio.ovl   (make a copy)
3. Click File > Save
4. Examine resulting file

**Expected behavior**
The game crashes because the ovl is broken. I believe the included ovl strings overrun the ovs header.

Adding a simple .txt file to the ovl fixes the problem.

**Screenshots**
Good OVL
![image](https://user-images.githubusercontent.com/28944639/198518602-c9aac74c-64c8-407a-8038-8481661af96e.png)

Wong OVL
![image](https://user-images.githubusercontent.com/28944639/198518663-62206fb5-dbfe-4beb-82b6-5c4d70cecba2.png)

**Version Info:**
 - Python version: 3.10
 - Cobra Tools Version [e.g. release x.xx, or master, date downloaded]
 
 **Log Files:**
 - No errors.

**Comment by ilodev** [comment]
Shall we say this is fixed now?

**Comment by HENDRIX-ZT2** [comment]
It is.
