### ISSUE TITLE
Blender: material rename causes false extra UV

### ISSUE THREAD

**Issue by harlequinzeg0** [OpenNaja/cobra-tools#261]
This issue was noticed on the triceratopsJWE.ovl model

Steps to reproduce:
1. Rename triceratops material to a longer name
2. Attempt to export file
3. Log will complain that triceratops_lod0_ob0 has 3 UVs but expected 2 despite only having 2 UVs

results in not being able to export the ms2.

**Comment by HENDRIX-ZT2** [comment]
Can't reproduce on my end. Renamed material to TriceratopsTest1234, exports fine.

**Comment by hexabits** [comment]
For posterity, it's specifically the addition of `_fur`

**Comment by harlequinzeg0** [comment]
is due to JWE trike having 2 UV's and _Fur material expects 1 + a fur UV so it ends up with 3,
