### ISSUE TITLE
MS2 - Feather "fur" texture reverse combing

### ISSUE THREAD

**Issue by rinrobi** [OpenNaja/cobra-tools#263]
**Describe the bug**
The fur texture is combed in the wrong direction after import

**To Reproduce**
1. Export a dino that has a fur texture in vanilla (eg. Pyroraptor, Therizinosaurus, etc)
2. Inject into ovl
3. Look in game or in Species Viewer (easier to see in SV)

**Expected behavior**
Fur to be combed in the correct direction it is in Blender and in vanilla

**Screenshots**
![Screenshot (96)](https://user-images.githubusercontent.com/116887550/198756536-bd98ebc7-50fd-4c7a-9ea2-2bda48ad613c.png)

**Version Info:**
 - Python Version: 3.10.7
 - Blender Version: 3.3.1
 - Cobra Tools Version: Master (has been prevalent since export fix)
 
 **Log Files:**
[ovl_tool_gui.log](https://github.com/OpenNaja/cobra-tools/files/9892611/ovl_tool_gui.log)

**Comment by HENDRIX-ZT2** [comment]
Yeah, looks good in my tests. Can be reopened if it does pop up again. We never figured out what caused it, lol

**Comment by rinrobi** [comment]
> Yeah, looks good in my tests. Can be reopened if it does pop up again. We never figured out what caused it, lol

Hey, as long as it's working I guess lol

**Comment by HENDRIX-ZT2** [comment]
It's apparently happening again. Perhaps randomly. Nobody knows

**Comment by HENDRIX-ZT2** [comment]
Fixed by accident?

New fur gauge code is more numerically stable (also after regenerating fins and exporting) and prevents fur unexpectedly growing ingame after calculating fins.
