### ISSUE TITLE
MS2 - Flickering fur textures post-injection

### ISSUE THREAD

**Issue by rinrobi** [OpenNaja/cobra-tools#264]
**Describe the bug**

After injection, patches on the fur texture flickers. See attachment

**To Reproduce**

1. Export a dino that has a fur texture in vanilla (eg. Pyroraptor)
2. Inject
3. Look in game or Species Viewer (easier to see in SV)

**Expected behavior**

No flickering, looking like vanilla

**Screenshots**

https://user-images.githubusercontent.com/116887550/198758793-04d01cd1-2b23-4a5e-9801-f85e0ea74583.mp4

**Version Info:**
 - Python Version: 3.10.7
 - Blender Version:3.3.1
 - Cobra Tools Version: Master
 
 **Log Files:**

[ovl_tool_gui.log](https://github.com/OpenNaja/cobra-tools/files/9892622/ovl_tool_gui.log)

**Comment by rinrobi** [comment]
Video had to be short due to file size. Can send a longer video with more angles on Discord if needed!

**Comment by HENDRIX-ZT2** [comment]
Injection of the model I presume?

**Comment by rinrobi** [comment]
Yes! Sorry I didn’t specify

**Comment by HENDRIX-ZT2** [comment]
@harlequinzeg0 this is likely due to the bad floats data on the chunks, so the sorting goes wrong

**Comment by ilodev** [comment]
that flickering looks to me like the are actually in the same exact position and fighting for the render order, could it be the float compression or something losing precission?

**Comment by HENDRIX-ZT2** [comment]
> that flickering looks to me like the are actually in the same exact position and fighting for the render order, could it be the float compression or something losing precission?

Yes, they are Z-fighting, but I think it is not due to precision issues in the mesh data but due to us feeding bad data for the sorting of chunks. Each chunk has a bunch of floats that I interpret as relevant for the Z sorting of chunks. That's the most likely explanation for why they implemented chunks in the first place. It's much faster to Z sort chunks than all polys of a mesh.

**Comment by harlequinzeg0** [comment]
issue is specific to the shell meshes

**Comment by HENDRIX-ZT2** [comment]
> issue is specific to the shell meshes

Have you tried actually deleting the shell meshes with the current patch - flickering is gone, then?

**Comment by HENDRIX-ZT2** [comment]
This appears to be due to the bad chunk splitting algorithm.

**Comment by harlequinzeg0** [comment]
fixed in commit that rewrote chunking
