### ISSUE TITLE
OVL - Crashes on extracting to OneDrive folder

### ISSUE THREAD

**Issue by rinrobi** [OpenNaja/cobra-tools#269]
**Describe the bug**

Trying to extract the contents of dino OVL, tools crashes and closes. OVL used was vanilla, and attempted several times on several dinos. Error messages in log, see attached

**To Reproduce**
1. Select a dinosaur OVL
2. Open OVL
3. Attempt to extract all files

**Expected behavior**

Files able to extract without crashing

**Screenshots**
N/A, see log

**Version Info:**
 - Python Version: 3.11
 - Blender Version: 3.3.1
 - Cobra Tools Version: Master
 
 **Log Files:**
[ovl_tool_gui.log](https://github.com/OpenNaja/cobra-tools/files/9894929/ovl_tool_gui.1.log)

**Comment by HENDRIX-ZT2** [comment]
Could you provide some samples (OVL+OVS) files that you get the crash on? Don't have my modding computer at hand.

**Comment by ilodev** [comment]
Can't reproduce Liv. I also saw that you used Unpack all and not dragging files out, I tried replicating that issue and I got the same log as you without any crash.

was there anything else you were also doing? like opening other ovls too then after some time one of them crashed? The log shows just opening one single ovl file, then extracting.

**Comment by rinrobi** [comment]
> Can't reproduce Liv. I also saw that you used Unpack all and not dragging files out, I tried replicating that issue and I got the same log as you without any crash.
> 
> was there anything else you were also doing? like opening other ovls too then after some time one of them crashed? The log shows just opening one single ovl file, then extracting.

I unpacked all with the previous master and had no issues. I tested this with several ovls, I just sent a clean log with only one crash in it, cause I figured it may be easier to look at

**Comment by rinrobi** [comment]
> Could you provide some samples (OVL+OVS) files that you get the crash on? Don't have my modding computer at hand.

[BaryonyxJWE.zip](https://github.com/OpenNaja/cobra-tools/files/9896353/BaryonyxJWE.zip)
[Allosaurus.zip](https://github.com/OpenNaja/cobra-tools/files/9896354/Allosaurus.zip)
[Albertosaurus.zip](https://github.com/OpenNaja/cobra-tools/files/9896355/Albertosaurus.zip)

**Comment by HENDRIX-ZT2** [comment]
Caused by exporting to a folder in OneDrive, but actual source of the error remains unknown.

**Comment by HENDRIX-ZT2** [comment]
Extracting all to a folder without permissions raises error as expected, and does not crash.

**Comment by HENDRIX-ZT2** [comment]
I can not replicate by extracting to OneDrive on my end.
