### ISSUE TITLE
Planet Zoo: Inconsistent normals from falsely identified mirrored UV (Again)

### ISSUE THREAD

**Issue by SleepyEngi** [OpenNaja/cobra-tools#273]
**Describe the bug**
It seems the bug with mirrored UV flag causing normals to invert is back again for a third round

**To Reproduce**
In this case, I made a scenery item from a animal material and model, but it should be identical to an actual animal. The object layout consists of the main body, which has no mirrored UVS, a model for the eyes (with  mirrored uvs) and a model for the tusks/teeth/tongue (also with mirrored uvs)
after checking it in-game, the normals seem inverted once again, after the issue had been fixed not long ago several times

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/59126707/199154904-9bf9bccb-3445-483b-95d6-1e2a52a6a45a.png)
Inverted normals in-game
![image](https://user-images.githubusercontent.com/59126707/199154960-abeca9f8-5953-4f53-a47b-59f0ffbeb38d.png)
Correct normals in blender after importing the model

**Version Info:**
 - Python Version: 3.7.9
 - Blender Version: 3.3
 - Cobra Tools Version [10/31/2022]
 
 **Log Files:**
 

Exported MS2 in question:
[php_reconstructions_01_.zip](https://github.com/OpenNaja/cobra-tools/files/9906689/php_reconstructions_01_.zip)

**Comment by HENDRIX-ZT2** [comment]
when I import that ms2, and export it again, the bitangent bit is cleared

**Comment by HENDRIX-ZT2** [comment]
For reference, the selection of another UV layer broke it. Needs to use the first, which is now set to me.calc_tangents(uvmap="UV0")
