### ISSUE TITLE
Codegen - Python 3.11 changes str(enum) behavior

### ISSUE THREAD

**Issue by rinrobi** [OpenNaja/cobra-tools#274]
**Describe the bug**

Extracting a tex file with python 3.11 messed up the compression type
Instead of "compression_type="DdsType.BC1_UNORM_SRGB"", it becomes "compression_type="79", and is unable to be injected

**To Reproduce**
1. Have python 3.11
2. Extract a tex file
3. Open the file and read the compression type

**Expected behavior**
compression_type="DdsType.BC1_UNORM_SRGB"

3.11
![Screenshot (104)](https://user-images.githubusercontent.com/116887550/199369683-c21c94b9-f452-4a6d-9d4f-f9772566918f.png)

3.10.7
![Screenshot (105)](https://user-images.githubusercontent.com/116887550/199369719-7c3f43c4-6c14-49ca-a7b8-29b57d032e54.png)

**Comment by HENDRIX-ZT2** [comment]
https://docs.python.org/3.12/whatsnew/3.11.html#enum

> Changed [IntEnum](https://docs.python.org/3.12/library/enum.html#enum.IntEnum), [IntFlag](https://docs.python.org/3.12/library/enum.html#enum.IntFlag) and [StrEnum](https://docs.python.org/3.12/library/enum.html#enum.StrEnum) to now inherit from [ReprEnum](https://docs.python.org/3.12/library/enum.html#enum.ReprEnum), so their [str()](https://docs.python.org/3.12/library/stdtypes.html#str) output now matches [format()](https://docs.python.org/3.12/library/functions.html#format) (both str(AnIntEnum.ONE) and format(AnIntEnum.ONE) return '1', whereas before str(AnIntEnum.ONE) returned 'AnIntEnum.ONE'.

**Comment by HENDRIX-ZT2** [comment]
Solution is probably using [repr()](https://docs.python.org/3.12/reference/datamodel.html#object.__repr__) instead of str()

**Comment by HENDRIX-ZT2** [comment]
Repr adds < >, gotta override or use custom implementation

**Comment by rinrobi** [comment]
fix didn't work? or was there another error

**Comment by harlequinzeg0** [comment]
reverted commit on master
