### ISSUE TITLE
Packed textures/materials issues

### ISSUE THREAD

**Issue by ilodev** [OpenNaja/cobra-tools#276]
**Describe the bug**
Testing out some blender stuff we realized there is something wrong with some of the textures. We are using: 
JWE2\Content2\Buildings\Shared\Materials\Decoration_Materials\Content2_Decoration_Materials

All sorts of issues here.. the normal maps seem to be packed but they are not unpacked as _RG, AO needs to discount the alpha, etc..

This is how textures unpacked
![image](https://user-images.githubusercontent.com/28944639/199470034-61e701af-30ab-4ba0-bb5b-81dd0a1dc71f.png)

I'm really not the best person to describe the issue thoroughly, but the discord convo linked at the end does it.

**Expected behavior**
Expected blender result:
![image](https://user-images.githubusercontent.com/28944639/199469412-3279e550-8343-4609-9024-1395eecaf23f.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/28944639/199469228-86a2f893-2b51-485f-a1df-fd0c954b64bf.png)

look in-game
![image](https://user-images.githubusercontent.com/28944639/199469273-ec703a83-d7dd-4585-b14b-f8cbc35e60c9.png)

**Version Info:**
 - Python Version: 3.10
 - Blender Version: 3.2
 - Cobra Tools Version just fresh
 
 **Log Files:**
 no errors on the logs

Discord conversation:
https://discord.com/channels/@me/795049282834268170/1037293521171918858

**Comment by HENDRIX-ZT2** [comment]
@hexabits @ilodev are there any issues that persist here?

**Comment by hexabits** [comment]
I checked several types of PZ scenery with no issues on latest.

**Comment by ilodev** [comment]
No, all good here
