### ISSUE TITLE
Herrerasaurus, Deinonychus and Australovenator (and perhaps more) breaks ingame when imported.

### ISSUE THREAD

**Issue by MisterFeilong** [OpenNaja/cobra-tools#277]
Neither Hyper, Lucca or Nano found out what causes this but seems to mainly happen with model ports (Ex: metri on herrera anims), randomly one of the model parts break, in case of australo or herrera any arm and in case of deinonychus, whole body.

**Comment by MisterFeilong** [comment]
they also lack LOD 4 and LOD 5

Cobra version: 6149bcf

**Comment by MisterFeilong** [comment]
![image](https://user-images.githubusercontent.com/105666109/199877734-75618318-d656-43b3-8359-49154ddebbb9.png)
Tested with 59f4ba1f
bug still happens

**Comment by HENDRIX-ZT2** [comment]
Not a tools bug but a naming issue on the original model according to @harlequinzeg0

**Comment by harlequinzeg0** [comment]
the right upper half twist arm node animation data seems to have been corrupted by frontier themselves and they covered it up by making them use the right upper arm node instead for that particular weight. entirely frontiers fault.
