### ISSUE TITLE
Can't save ms2 hitbox model

### ISSUE THREAD

**Issue by ilodev** [OpenNaja/cobra-tools#278]
**Describe the bug**
Pluging giving errors when saving this one. ovldata\Content0\Buildings\Buildings\GST_EmergencyShelter\gst_emergencyshelter_navigation_.ms2

**To Reproduce**

1. import the ms2 (it is vanilla extracted)
2. export the ms2,  check 'edit bones'
3. ?

**Screenshots**
![image](https://user-images.githubusercontent.com/28944639/200057636-301b4ed3-967f-4bc3-a090-a1ec0d502adb.png)

[gst_emergencyshelter_navigation_.zip](https://github.com/OpenNaja/cobra-tools/files/9941385/gst_emergencyshelter_navigation_.zip)

**Comment by HENDRIX-ZT2** [comment]
It's a long name issue

**Comment by HENDRIX-ZT2** [comment]
Fixed by adding the long_name custom property on import, and export uses that to find the right joint.

**Comment by ilodev** [comment]
oh thanks hendrix, I thought to document the solution as to:
- rename model in ovl before extract
- import/do/export
- inject and rename back again

But if you made a fix then we are good!
