### ISSUE TITLE
AssertionError，when I try to open Mains.ovl in contend0(JWE2)

### ISSUE THREAD

**Issue by 2239614634plr** [OpenNaja/cobra-tools#279]
Hi，when I try to use the new cobra tools to open Main.ovl in contend0(JWE2).The tools breaking.
 Python Version: 3.7.9
![屏幕截图(8)](https://user-images.githubusercontent.com/111658859/200841737-5020a82d-a2eb-4604-8ba7-6290af828273.png)

**Comment by HENDRIX-ZT2** [comment]
Verify files and try again.

**Comment by 2239614634plr** [comment]
> Verify files and try again.

I've tried many times.

**Comment by HENDRIX-ZT2** [comment]
Getting no error on my end for content0 main with freshly updated files.

**Comment by 2239614634plr** [comment]
> 使用最新更新的文件对 content0 main 没有任何错误。
Thank you,I will try again

**Comment by 2239614634plr** [comment]
> 使用最新更新的文件对 content0 main 没有任何错误。
Thank you ,I will try again

**Comment by 2239614634plr** [comment]
> Getting no error on my end for content0 main with freshly updated files.

Oh ,I used the freshli updated files,but the I still can't open the contend0
![屏幕截图(9)](https://user-images.githubusercontent.com/111658859/200873226-0286d840-ff99-4114-9515-07b586743715.png)

**Comment by HENDRIX-ZT2** [comment]
Post the complete ovl_tool_gui.log file please.

**Comment by 2239614634plr** [comment]
[ovl_tool_gui.zip](https://github.com/OpenNaja/cobra-tools/files/9972633/ovl_tool_gui.zip)

**Comment by 2239614634plr** [comment]
> Post the complete ovl_tool_gui.log file please.

ok thank you

**Comment by 2239614634plr** [comment]
[ovl_tool_gui.log](https://github.com/OpenNaja/cobra-tools/files/9972641/ovl_tool_gui.log)

**Comment by HENDRIX-ZT2** [comment]
Well, I can tell from the log that your Main.ovs.models_l0 is not original, as it says:
INFO | Compressed stream Models_L0 in Main.ovs.models_l0 starts at 0
DEBUG | Compression magic bytes: b'x\x9c'

The original should say:
DEBUG | Compression magic bytes: b'\x8c\x06'

**Comment by 2239614634plr** [comment]
emmm
Could I ask you that what should I do next?

**Comment by HENDRIX-ZT2** [comment]
Delete the Main.ovs.models_l0 file, verify files, try again.
This is not a tools issue.
