### ISSUE TITLE
FGM Finding: pDecayNormalConstrastScale

### ISSUE THREAD

**Issue by Lucca2951** [OpenNaja/cobra-tools#28]
Only tested on JWE dinosaurs, while editing their main fgm file, in this case "ouranosaurus.fgm", there is a section focused on the decay attributes for the model, diffuse color, normal map intensity, etc etc, the one that i tested was the pDecayNormalConstrastScale, which changes how intense the normals become on the dead body, the default value is 1,500 while i tested with 5,000; not sure if there's a limited value so far
![c9009b10513eee62088e2854bb4befc5](https://user-images.githubusercontent.com/20666228/71648469-572d3400-2ce3-11ea-9a7f-d2fc7c54ec14.jpg)
![2923a09bb1ea121c7ee902fc337e9e47](https://user-images.githubusercontent.com/20666228/71648474-5d231500-2ce3-11ea-8e9a-aa30c1710f92.jpg)

**Comment by HENDRIX-ZT2** [comment]
Thanks! Added to tooltips.
