### ISSUE TITLE
Unable to create LODs for dinosaurs with fur

### ISSUE THREAD

**Issue by rinrobi** [OpenNaja/cobra-tools#282]
**Describe the bug**
When trying to use the "Create LODs" tool in Blender for any dinosaur with fur, Blender gives an error "Index out of range"

I know you guys are aware of this! I am making an issue report to keep everything consistent and so everything is recorded for publically!

Huge thanks to Pokemonfan2750 for the help getting everything together while I am away from home! 
Tested on: Therizinosaurus, Pyroraptor, and TyrannosaurusRexFeathered

**To Reproduce**
1. Import any dinosaur with a fur object
2. Attempt to create LODs using the tool
3. See error

**Expected behavior**
No error, with LODs successfully created

**Screenshots**
N/A

**Version Info:**
 - Python Version: 
Me: 3.10.7 
Pokemon: 3.7.9

 - Blender Version:
Me: 3.3.2
Pokemon: 3.2
 - Cobra Tools Version: Master, but occurs on all previous versions
 
 **Log Files:**
Tools log N/A
[blender_plugin.log](https://github.com/OpenNaja/cobra-tools/files/10004618/blender_plugin.2.1.log)

**Comment by HENDRIX-ZT2** [comment]
Fixed!
