### ISSUE TITLE
Editing dino stats crashes game

### ISSUE THREAD

**Issue by manbeastsaviorofthemoon** [OpenNaja/cobra-tools#288]
**Describe the bug**
hello, so pretty much every update before i used cobra tools and SQLiteStudioto unpack, edit, inject and save the c0dinosaurs.fbd SpeciesCombat table data over the Main.ovl in Content0. solely for the t-rex changing their AttackMin + AttackMax of 109 and DefenseMin + DefenseMax of 30 all to 1000. i reduced it to 500 each and it still crashes. i need the unchanged Main.ovl in order for the game to not crash on the powered by Cobra logo

**Version Info:**
 - Python Version: 3.9.13
 - SQLiteStudio 3.4.1
 - Cobra Tools Version 2.4.0 Jun 10

**Comment by HENDRIX-ZT2** [comment]
Probably outdated tools?
