### ISSUE TITLE
.tex file extraction error

### ISSUE THREAD

**Issue by Turtle513** [OpenNaja/cobra-tools#289]
**Describe the bug**
When extracting/unpacking .ovl files to a folder, .tex files won't be extracted due to an error.

**To Reproduce**
Open an .olv file and unpack it to any folder.

**Expected behavior**
.tex files should be extracted as well as their affiliated files.

**Screenshots**
![Screenshot (423)](https://user-images.githubusercontent.com/120400623/207092345-29a76798-8282-46d5-ba40-5e86b64869a2.png)

![Screenshot (422)](https://user-images.githubusercontent.com/120400623/207091180-92976f63-b372-4b56-b4fb-ca6653b69947.png)

**Version Info:**
 - Python Version 3.7.7
 - Cobra Tools Version 2.4.0 (Dec 10th 2022)

 **Log Files:**
[ovl_tool_gui.log](https://github.com/OpenNaja/cobra-tools/files/10209707/ovl_tool_gui.log)

**Comment by HENDRIX-ZT2** [comment]
Follow installation instructions and read the top of your log file.
