### ISSUE TITLE
Creating an OVL or injecting an FGM in an ovl make the game crash.

### ISSUE THREAD

**Issue by ilodev** [OpenNaja/cobra-tools#291]
**Describe the bug**
Creating an OVL or injecting an FGM in an ovl make the game crash.

**To Reproduce**
Re-creating any of the game ovls with fgms in it should trigger the error. The game crashes when it loads the new ovls generated.

I can confirm that just loading the ovl makes the game crash even not using the fgm in it by any model.
I changed a game prefab to include a new created ovl with one new fgm in it and the game crashed when spawned the asset.

**Expected behavior**
not crashing, definitely :)

**Version Info:**
all latest
 
 **Log Files:**
No errors in log files

 **Extra Files**
I'm attaching the generated OVL from my tests in case it helps

[TestMats.zip](https://github.com/OpenNaja/cobra-tools/files/10247863/TestMats.zip)

**Comment by harlequinzeg0** [comment]
Fixed with commit 9ca1330, the issue was the implementation of the offsetstring. Unsure why it is broken but I have reverted to the previous method.

**Comment by ilodev** [comment]
Jesse, can you ask radrr to test it, he has a working case he can validate
as fixed.
Thanks for the revert tho, we’ll see how to redo the offset string change
later on

**Comment by RADRR1985** [comment]
thanks, I have tested and this is problem is now fixed.

**Comment by ilodev** [comment]
You guys are the best!
