### ISSUE TITLE
AllosaurusJW does not have a pack base value

### ISSUE THREAD

**Issue by rinrobi** [OpenNaja/cobra-tools#292]
AllosaurusJW uses the airstraps from the regular JWE Allosaurus, so the scene does not have its own mesh. The scene pack base value is 0 and cannot export because of this! I changed it to the 512 myself, and it exported just fine once I did, but I figured you guys might wanna know!
![Screenshot (472)](https://user-images.githubusercontent.com/116887550/208276295-00e372f9-e5d5-4a42-bb69-61007ab28562.png)

**Comment by harlequinzeg0** [comment]
okay we need to do a check if there is even mesh data present in that scene, otherwise it should accept the pack base of 0
