### ISSUE TITLE
jurrasic world evo 2 error

### ISSUE THREAD

**Issue by goryfreak** [OpenNaja/cobra-tools#293]
inside in the ovldata folder from game files there is a folder named content 0 inside is a  file named main.ovl
so with cobra tools im able to mod the values of certain options inside the game but with last game update the app is not able to open the file to inject the cofiguration, shows an error 
![Captura de pantalla 2022-12-18 232330](https://user-images.githubusercontent.com/121003735/208354176-0dcff597-c62b-408a-af64-7190933a4134.png)
![Captura de pantalla 2022-12-18 232358](https://user-images.githubusercontent.com/121003735/208354193-55b41ca1-e368-4443-844a-93a27b87afeb.png)

**Comment by HENDRIX-ZT2** [comment]
It's not a tools issue per se - the ovl does not agree with the ovs file you had. That happens when an update rolls out changes to an ovl only, but you had a modified ovl and ovs before the update. Verify files to get the correct ovs.
