### ISSUE TITLE
Hitbox injection and creating new OVLs doesn't work

### ISSUE THREAD

**Issue by RADRR1985** [OpenNaja/cobra-tools#298]
**Describe the bug**
Injection and creation new OVLs with 3 hitboxes (scenery.ms2 spatial.ms2 and navigation_.ms2) doesn't work in Jurassic World Evolution 2 after the Malta DLC update

**To Reproduce**

Injection
======
1. Extract files in \Jurassic World Evolution 2\Win64\ovldata\Content2\Buildings\Decorations\DEC_ConcreteBarrier\DEC_ConcreteBarrier.ovl
2. Without doing any changes to scenery.ms2 spatial.ms2 and navigation_.ms2 inject them back into the OVL
3. This will remove the existing scenery.ms2 spatial.ms2 and navigation_.ms2 in the ovl file and fail to inject these same ms2 files extracted before 
4. Error in the Log is attached

New OVL
======
1. Extract files in \Jurassic World Evolution 2\Win64\ovldata\Content2\Buildings\Decorations\DEC_ConcreteBarrier\DEC_ConcreteBarrier.ovl
2. Without doing any changes to scenery.ms2 spatial.ms2 and navigation_.ms2 Create a new OVL that includes all the files you extracted
4. This will exclude the scenery.ms2 spatial.ms2 and navigation_.ms2 in the ovl file due to the error.
5. Error in the Log is attached

**Expected behavior**
Inject/create an ovl with scenery.ms2 spatial.ms2 and navigation_.ms2 files

**Screenshots**
N/A

**Version Info:**

python 3.9.5
imageio 2.21.0
cobra-tools 2.5.0 stable version, 14f13c7 - Mon Dec 19 00:17:00 2022 +0100
 
 **Log Files:**
 - Attached
 - 
[ovl_tool_gui.log](https://github.com/OpenNaja/cobra-tools/files/10341512/ovl_tool_gui.log)

**Comment by ilodev** [comment]
confirmed as fixed for me. Great job Hendrix.

Note: can we demote the message to a warning? it is still treated as error

**Comment by ilodev** [comment]
There seems to still be a problem with this, reopening as requested by @RADRR1985

**Comment by HENDRIX-ZT2** [comment]
Yup, the codegen should create pointers to store empty arrays still. That may cause trouble for our implementation of other formats, but it is the standard used by fdev.

**Comment by HENDRIX-ZT2** [comment]
Is apparently fixed now, but may have messed with other formats. The behavior mimics fdevs tools now.
