### ISSUE TITLE
OVL - FGRK format (RCT3, Wallace & Gromit, Dog's Life ?)

### ISSUE THREAD

**Issue by TheMaskedMan00** [OpenNaja/cobra-tools#300]
I try to extract a ovl from roller coaster tycoon 3
->  ovl unpack requires a buffer of 4 bytes
here are files:
https://drive.google.com/drive/folders/1ffZNGbOoGUxr2uHXYcb1d3joYJ7j9F2J?usp=share_link

and log 
[ovl_tool_gui.log](https://github.com/OpenNaja/cobra-tools/files/10543380/ovl_tool_gui.log)

**Comment by HENDRIX-ZT2** [comment]
http://wiki.xentax.com/index.php/RollerCoaster_Tycoon_3_OVL

http://wiki.xentax.com/index.php/Game_Extractor

https://rct3.sourceforge.net/tutorials/beginner_tutorial.html

https://github.com/gamemodderz/OVLExtractor-2

**Comment by ilodev** [comment]
https://sourceforge.net/projects/rct3/files/OvlMake/

**Comment by ilodev** [comment]
https://github.com/noaharoth/RCT3PathCreator
