### ISSUE TITLE
Unpack Requires a Buffer of one Bytes error

### ISSUE THREAD

**Issue by dtb01-77** [OpenNaja/cobra-tools#302]
Hello, I am trying to open and modify a .OVL file for a car radio head unit. Yes, I know this is pretty far from what Cobra-Tools is for, but I have not found anything else useful in opening these types of files, but if anyone has any suggestions please let me know. All I am trying to do is edit a few images in the .OVL, and I know that the images are there because I can see named .png files when I open the OVL using note pad. Anyways, when I try to open the .OVL file in Cobra tools I get the following an unpack requires a buffer of one bytes error. Please let me know if you have any ideas on how to fix this. 
The contents of the olv_tool_gui text file with the debug and error in it is linked below

https://docs.google.com/document/d/14zvdwflz8V9sR98aygRlUq0FNLjEcbx0FwS8GrCAurI/edit?usp=sharing

Thank you!

**Comment by HENDRIX-ZT2** [comment]
What game is this?

**Comment by dtb01-77** [comment]
> What game is this? You should provide a sample file, since it doesn't seem to be one of the supported games.

it is not a game. It is in fact an OVL for the program for a touchscreen car radio. I will attach the file below

https://drive.google.com/file/d/1-HSBFgMcmFWC4k4SvJl_mN_ktl_Y8zcj/view?usp=sharing

**Comment by HENDRIX-ZT2** [comment]
Totally unrelated file format, as expected.
You'll need to reverse engineer the structure of 'your' OVL format to be able to modify it.
