### ISSUE TITLE
Can't install cobra tool 2.5 into blender 3.2 " module not found error: no module named cobra 2 "

### ISSUE THREAD

**Issue by Plaston** [OpenNaja/cobra-tools#306]
**Describe the bug**
Can't install cobra tool 2.5 into blender 3.2 " module not found error: no module named cobra 2 ".

**To Reproduce**
1. Go to Download the addon 2.5 release
2. Install the addon with blender 3.2
3. Module not found

**Expected behavior**
Install the addon's zip file

**Version Info:**
 - Python Version: [3.11]
 - Blender Version: [3.2]
 - Cobra Tools Version [2.5]

**Comment by HENDRIX-ZT2** [comment]
Don't use the release zip file. Blender breaks from the dots in the versions in the folder names. Either rename the folder, or just use a master zip file.
