### ISSUE TITLE
Threaded call errored

### ISSUE THREAD

**Issue by RommelHeinz3** [OpenNaja/cobra-tools#316]
**Describe the bug**
Unable to extract c0dinosaur file from main, also fails in injection

**To Reproduce**
Open the main file, it shows Threaded call errored! Then it cannot be extracted from the main file
**Expected behavior**
unable to extract

**Screenshots**
![c5164d2bcd7370c3b093a4f7d9c301f](https://user-images.githubusercontent.com/107663480/229344180-34a58687-8cc5-4e79-9608-d928e19ea1ed.png)

**Version Info:**
 - Python Version: [e.g. 3.11.2]
 - Blender Version: [e.g. 2.92]
 - Cobra Tools Version [Sat April 1 23:16:43]
 
 **Log Files:**
 - Close the tools and attach the appropriate log file here. [e.g. cobra-tools/ovl_tool_gui.log]
[ovl_tool_gui.log](https://github.com/OpenNaja/cobra-tools/files/11131717/ovl_tool_gui.log)

**Comment by HENDRIX-ZT2** [comment]
Needs more information. Steps to reproduce is incomplete.

**Comment by HENDRIX-ZT2** [comment]
Appears to be a saving issue unrelated to the fdb. Should be fixed now!

**Comment by HENDRIX-ZT2** [comment]
I didn't notice the complete log, so for reference:
Verify files. Your OVL was modified before the update and partially rolled over by the update (the ovs is the modified version still).
