### ISSUE TITLE
I can't open main.ovl in conent0 - Jurassic World Evolution 2 V1.71

### ISSUE THREAD

**Issue by plsalain** [OpenNaja/cobra-tools#317]
Same as : https://github.com/OpenNaja/cobra-tools/issues/316

here is my log file

Thank you.
Alain
[ovl_tool_gui.log](https://github.com/OpenNaja/cobra-tools/files/11134265/ovl_tool_gui.log)

**Comment by HENDRIX-ZT2** [comment]
Verify files. Your OVL was modified before the update and partially rolled over by the update (the ovs is the modified version still).

**Comment by plsalain** [comment]
Thank you !
