### ISSUE TITLE
installation into blender

### ISSUE THREAD

**Issue by LeSloth1** [OpenNaja/cobra-tools#318]
when installing cobra tools into blender this message occurs
![Blender Preferences 04_04_2023 20_26_12](https://user-images.githubusercontent.com/129898871/229903644-179749a0-373b-4b73-a2e2-f45658fc8586.png)
im unsure what it means and i have tried to install multiple times but doesnt work. i have installed latest version of blender and cobra tools and tried my best to fix it

**Comment by HENDRIX-ZT2** [comment]
Sounds like you have several copies of the plugin in your addons folder already?

**Comment by LeSloth1** [comment]
> Sounds like you have several copies of the plugin in your addons folder already?

No I only have 1 cobra tools installed in blender addons

**Comment by HENDRIX-ZT2** [comment]
If you have older blender versions installed, remove it from those addon folders too.
Look into your blender addon folder (path is in the screenshot you posted) and make sure that's the only copy of the plugin you have in there.
If that doesn't help after restarting blender, just put in the tools folder manually, restart blender, and then just activate it with the checkbox in user prefs.

**Comment by HENDRIX-ZT2** [comment]
Feel free to explain what solved the problem on your end for others running into the same issue.
