### ISSUE TITLE
JWE2 .ms2 import or export issue

### ISSUE THREAD

**Issue by Kaiodenic** [OpenNaja/cobra-tools#319]
This seems a bit random and most of the files I tried worked perfectly fine. However, Walls.ovl (Jurassic World Evolution 2\Win64\ovldata\Content0\Buildings\SplineBased\Walls\Walls.ovl) breaks its models up between three files and some streams;
- models1lod.ms2
- models2lods.ms2
- models2lods0.model2stream
- models3lods.ms2
- models3lods0.model2stream
- models3lods1.model2stream

**models1lod.ms2** and **models2lods.ms2** seem to work fine and can be exported, edited, and imported again. **models3lods.ms2** and its model2streams, however, causes an in-game crash if it is exported and then imported again. I tried this using both the current branch from about an hour ago (05/04/2023), as well as a build from around 08/03/2023. In today's build, the models can be exported and re-imported, and there doesn't appear to be any extra issues on top of that until the in-game crash.

The older build was more obvious because if you
- Opened Walls.ovl
- Exported models3lods.ms2
- Imported models3lods.ms2
- Opened another .ovl
- Opened Walls.ovl again
Then tried to export models3lods.ms2 again, Cobra Tools would throw out an error.

Edit: On further testing, there is still an in-Cobra-Tools tell of the error. If you
- Open Walls.ovl
- Export models3lods.ms2
- Import models3lods.ms2
Then trying to import models3lods.ms2 again will throw out the following error:

Traceback (most recent call last):
  File "G:\JWE2 Modding\Cobra Tools 12\generated\formats\ovl\__init__.py", line 649, in add_files
    self.register_loader(loader)
  File "G:\JWE2 Modding\Cobra Tools 12\generated\formats\ovl\__init__.py", line 663, in register_loader
    old_loader.remove()
  File "G:\JWE2 Modding\Cobra Tools 12\modules\formats\BaseFormat.py", line 257, in remove
    pool.offsets.remove(offset)
KeyError: 14864

Hope this covers everything, and it's not just me doing something stupid! I haven't worked with .ms2 files in a while so I may be exporting/importing those files into the tools wrong. However, this is all done without any Blender editing.

**Comment by HENDRIX-ZT2** [comment]
Probably related to #311. What happens without involving blender at all, ie. just injection?

**Comment by Kaiodenic** [comment]
That's right yeah, just standard unpacking/injection. My bad, I had a scan through the other bugs but didn't notice the PZ one!

**Comment by HENDRIX-ZT2** [comment]
Apparently fixed by removing the poorly implemented pool size condition.
