### ISSUE TITLE
Electric Tour Issue

### ISSUE THREAD

**Issue by DJNormality** [OpenNaja/cobra-tools#32]
Having a problem opening the .MDL2 file to the Electric Tour. This is my error.
![christ2](https://user-images.githubusercontent.com/59482618/71736522-484b9c00-2e1f-11ea-8903-5dd50479457c.png)
Anyone know whats going on here ?

**Comment by HENDRIX-ZT2** [comment]
Can't reproduce with latest code, fixed.

**Comment by DJNormality** [comment]
Do what ?
