### ISSUE TITLE
The blender plugin won't load, I folloed all the steps and the actual cobra software loads fine, just the blender addon. 

### ISSUE THREAD

**Issue by Elysisy** [OpenNaja/cobra-tools#329]
![image](https://user-images.githubusercontent.com/73320555/233814463-65cd3f36-a007-4a40-ae83-49cd2b1d5152.png)

**Comment by HENDRIX-ZT2** [comment]
Q: I install tools release zip file in blender and get this error.
A:  This error is due to the name that github gives the release and blender does not like. You either rename the zip and inside the zip to get rid of the '.' or you download master.
