### ISSUE TITLE
Cobra tools Unable to read main.ovl

### ISSUE THREAD

**Issue by leihahahaha** [OpenNaja/cobra-tools#333]
**Describe the bug**
Cobra tools Unable to read main.ovl and inject
prompt：WARNING | vdf not installed, can not detect steam games on external drives - run `pip install vdf`
but I have already installed vdf
I have tried all Python versions（3.7,3.8,3.9,3.11）

**Screenshots**
![_ALJLF_50072 3RMF3L@( Q](https://github.com/OpenNaja/cobra-tools/assets/134468512/13e10a9d-140e-4661-b3eb-210f8baa584c)

![IZ3LE9{@IT5B6OC KI7L{)D](https://github.com/OpenNaja/cobra-tools/assets/134468512/8c593915-b214-40fa-87b4-568bfcbefdae)

![H0C(~%JH@N`EKPWV9CWB PQ](https://github.com/OpenNaja/cobra-tools/assets/134468512/243c2d0d-989d-4ed0-9e74-6ab29136008e)

**Version Info:**
 - Python Version: [e.g. 3.7,3.8,3.9,3.11]
 - Blender Version: []
 - Cobra Tools Version [ 2.5.0, 2c71f640 - Mon May 22 07:50:07 2023 +0200]

**Comment by HENDRIX-ZT2** [comment]
It did open the main ovl. The error about vdf may be misleading.
