### ISSUE TITLE
ModuleNotFound Error : Segment

### ISSUE THREAD

**Issue by paww81** [OpenNaja/cobra-tools#334]
We are trying to install the Blender plugin for cobra-master-tools.  I have Blender 3.2.2 and Python 3.11.3.  I have tried to add the plug in on Blender 3.4 and 3.5 with the same exact error every time.    The error traces back with ModuleNotFound for Segment (see attached ovl tool log).  I ran the required pip install and it said it was completed.  However, I see in the ovl_tool_gui log that it is saying some Modules may be missing ??  What am I doing wrong?

**Version Info:**
 - Python Version: [e.g. 3.11.3]
 - Blender Version: [e.g. 3.2.2]
 - Cobra Tools Version [cobra-master-tools, downloaded 5/27/23]
 
 **Log Files:**
 - Close the tools and attach the appropriate log file here. [e.g. cobra-tools/ovl_tool_gui.log]

[ovl_tool_gui.log](https://github.com/OpenNaja/cobra-tools/files/11582945/ovl_tool_gui.log)

**Comment by HENDRIX-ZT2** [comment]
Nothing wrong on your end, the file had not been added by mistake. Redownload and it will work.

**Comment by paww81** [comment]
Thank you for the quick response.  I did redownload and am now getting a new bitstring error.  Please see attached log.  Thank you.

[ovl_tool_gui.log](https://github.com/OpenNaja/cobra-tools/files/11583019/ovl_tool_gui.log)

**Comment by HENDRIX-ZT2** [comment]
try again now

**Comment by paww81** [comment]
It worked!  Thank you.
