### ISSUE TITLE
Old Cobra Master tools version needed

### ISSUE THREAD

**Issue by SMBSGamerTamil** [OpenNaja/cobra-tools#335]
Hello team
This is not an issue and I need assistance. Could you please help with the best Cobra master tool version which I can use it for JWE2 before the Biosyn DLC release?
Thanks,

**Comment by HENDRIX-ZT2** [comment]
Try current master.

**Comment by ilodev** [comment]
Before biosyn DLC? which game version is this? 1.3.x?

**Comment by SMBSGamerTamil** [comment]
yes, it is version 1.3.1.36069_INT
