### ISSUE TITLE
AttributeError: 'BaseFile' object has no attribute 'extract'

### ISSUE THREAD

**Issue by NomadWithoutAHome** [OpenNaja/cobra-tools#338]
**Describe the bug**
AttributeError: 'BaseFile' object has no attribute 'extract'

**To Reproduce**
1. Go to 'any .ovl.'
2. Click on 'unpack all'
3. See error

**Expected behavior**
extract contents with no errors

**Version Info:**
 - Python Version: [3.11.4]
 - Cobra Tools Version [7/11/2023]
 
 **Log Files:**

[ovl_tool_gui.log](https://github.com/OpenNaja/cobra-tools/files/12021308/ovl_tool_gui.log)
[ovl_tool_gui.log](https://github.com/OpenNaja/cobra-tools/files/12021321/ovl_tool_gui.log)

**Comment by HENDRIX-ZT2** [comment]
The only apparent error is with the datastreams file, which has no support at the moment

**Comment by NomadWithoutAHome** [comment]
I got gotcha my bad after, fiddling with it i got everything i wanted to work just fine!
