### ISSUE TITLE
Program won't launch

### ISSUE THREAD

**Issue by stargatedalek** [OpenNaja/cobra-tools#35]
I have C++ and Python installed, but opening ovl_tool.bat a window briefly flickers then closes. Launching as administrator had no effect.

Is there something I should change in the config file? Does it matter what drive I have the program on?

**Comment by HENDRIX-ZT2** [comment]
Probably haven't installed the python dependencies. Run via command prompt or powershell to see the error.

**Comment by stargatedalek** [comment]
I opened it in powershell and this came up.

PS C:\Users\****> "E:\Games\Game Utilities\JWE Mods\cobra-tools\cobra-tools\ovl_tool.bat"
E:\Games\Game Utilities\JWE Mods\cobra-tools\cobra-tools\ovl_tool.bat
PS C:\Users\****>

I moved it to C drive and managed to get an error, so something happening might be drive ID dependent (which could likely be powershell, I don't know much about it).

C:\Users\****\Desktop\cobra-tools\ovl_tool.bat

C:\Users\****>python ovl_tool_gui.py
python: can't open file 'ovl_tool_gui.py': [Errno 2] No such file or directory
PS C:\Users\****>

**Comment by HENDRIX-ZT2** [comment]
If you type `python ovl_tool_gui.py` the cmd has to be in the folder that contains ovl_tool_gui.py (ie. cobra-tools). You can shift-right click in the cobra-tools folder to open a powershell there.

**Comment by stargatedalek** [comment]
Thanks for the shift-right click trick.

PS E:\Games\Game Utilities\JWE Mods\cobra-tools\cobra-tools> python ovl_tool_gui.py
Traceback (most recent call last):
  File "ovl_tool_gui.py", line 4, in <module>
    from PyQt5 import QtWidgets, QtGui, QtCore
ModuleNotFoundError: No module named 'PyQt5'
PS E:\Games\Game Utilities\JWE Mods\cobra-tools\cobra-tools>

I'm still not quite certain what to do from here. I need a python module named "PyQt5" I presume, but there seems to be dozens of python related modules or add-ons with that name.

**Comment by HENDRIX-ZT2** [comment]
Run a cmd with admin rights and install the following python modules using the given `pip` commands:
- pyffi 2.2.4.dev3 (run: `pip install PyFFI==2.2.4.dev3`)
- pyqt5 (run: `pip install pyqt5`)
- imageio (run: `pip install imageio`)

**Comment by HENDRIX-ZT2** [comment]
Update: you don't have pyffi 2.2.4.dev3 installed but some earlier version of pyffi. Must be dev3 so run: `pip install PyFFI==2.2.4.dev3`

**Comment by stargatedalek** [comment]
That got it working! Thanks so much for the help.
