### ISSUE TITLE
FGM Editor not saving files

### ISSUE THREAD

**Issue by Nekonotaishou** [OpenNaja/cobra-tools#351]
**Describe the bug**
FGM editor tool is not saving files.

**To Reproduce**
Load an existing FGM file, modify it, click save, or save as and rename. What happens is no file is overwritten, no new files is created. Opening the original file after hitting "save" opens a file that has not been modified at all.

**Expected behavior**
I expected a new FGM file to be saved

**Version Info:**
 - Python Version:  3.11.4
 - Cobra Tools Version 2.5.0

**Comment by HENDRIX-ZT2** [comment]
Hey, long time no talk! You helped me with some sauropod anims years ago.
Can reproduce the error, I'll try to fix it...

**Comment by HENDRIX-ZT2** [comment]
Fixed, just redownload! :)

**Comment by Nekonotaishou** [comment]
I remember that! Wow that was a long time ago.

Thank you! :D
