### ISSUE TITLE
Plugin Updater stopped working

### ISSUE THREAD

**Issue by ilodev** [OpenNaja/cobra-tools#356]
**Describe the bug**
Just reads: no preference.

**To Reproduce**
1. install plugin
2. expand plugin info in prefs
3. a warning will be show under the add-on info

**Expected behavior**
a bunch of buttons to auto-update or update the addon

**Comment by ilodev** [comment]
if hasattr(context, "user_preferences"):
        prefs = context.user_preferences.addons.get(__package__, None)

__package__ here is 'plugin' and not 'cobra-tools'

but if we change that, it will make install the update inside the plugin folder.

**Comment by ilodev** [comment]
it is like for some reason, only wants to operate within  '/plugin' like if this was the package it is installed

**Comment by HENDRIX-ZT2** [comment]
fixed, I think

**Comment by ilodev** [comment]
you are the best :)
