### ISSUE TITLE
Bulk Txt injection causes trouble

### ISSUE THREAD

**Issue by HENDRIX-ZT2** [OpenNaja/cobra-tools#36]
Probably padding is not 100% correct.
Proposed fix - store old padding (with OSUD etc) and then pad the result to multiples of 8 bytes:
pointer.update_data(new_txt_bytes+pointer.padding, pad_to=8)

**Comment by HENDRIX-ZT2** [comment]
Probably fixed.

**Comment by harlequinzeg0** [comment]
seems to be fixed
