### ISSUE TITLE
loc_tool_gui.py Crashes On windows 11 with error min_width being an unexpected argument.

### ISSUE THREAD

**Issue by ned228** [OpenNaja/cobra-tools#363]
loc_tool_gui.py Crashes On windows 11 with error min_width being an unexpected argument.

**To Reproduce**
1. The Extracted location of the Cobra Tools Files.
2. Click on '.loc_tool_gui.py.'
3.

**Expected behavior**
That the program will launch and run normally without crashing.

**Screenshots**
![Screenshot 2023-12-22 152454](https://github.com/OpenNaja/cobra-tools/assets/12898493/838291dc-4bd7-4150-b5ff-496a55e1c195)
**Version Info:**
 - Python Version: [e.g. 3.11.7]
 - Blender Version: [e.g. 3,6]
 
 
 **Log Files:**
 - [loc_tool_gui.log](https://github.com/OpenNaja/cobra-tools/files/13756773/loc_tool_gui.log)

**Comment by HENDRIX-ZT2** [comment]
Fixed that, but as far as I can tell, the loc tool is not useful for anything yet. You probably want the OVL tool instead.
