### ISSUE TITLE
MANIS - JWE1 error on injection

### ISSUE THREAD

**Issue by JosebaJWE** [OpenNaja/cobra-tools#366]
**Describe the bug**
An error that appears when injecting a MANIS file from JWE1 into another OVL of the game.

**To Reproduce**
1. Open a Dinosaur OVL (Unsure if this affects all OVLs containing manis) and unpack a mani file.
2.  When injected back without any further changes, you get an error on the console. (Shown on the **Log Files** section)

**Expected behavior**
It should inject without any further issues.

**Version Info:**
 - Python Version: 3.11.7
 - Cobra Tools Version: 2194c773e
 
 **Log Files:**
[ovl_tool_gui.log](https://github.com/OpenNaja/cobra-tools/files/13902016/ovl_tool_gui.log)

**Comment by HENDRIX-ZT2** [comment]
manis spec apparently does not work for JWE1

**Comment by HENDRIX-ZT2** [comment]
possibly fixed in https://github.com/OpenNaja/cobra-tools/commit/704cb0fa70e4592de76fc62bc64e21eb06d74b95
needs testing

**Comment by HENDRIX-ZT2** [comment]
Tested by @JosebaJWE, apparently working
