### ISSUE TITLE
Font Files?

### ISSUE THREAD

**Issue by skalia16** [OpenNaja/cobra-tools#374]
Hello, will there be support for importing ''ttf and ''otf'' font files?
Not being able to import fonts is really a big deficiency.
I would be very happy if you add this support.
Also thanks for this nice tool.

**Comment by hexabits** [comment]
Font files are streamed in through a complicated binary .FCT file that we haven't really been able to decode. I'm actually not sure the .TTF/.OTF are used directly, they may only be parsed using information from the .FCT file.

**Comment by HENDRIX-ZT2** [comment]
Actually, you should be able to replace font files by replacing those that come with an fct file and injecting again.

**Comment by hexabits** [comment]
> Actually, you should be able to replace font files by replacing those that come with an fct file and injecting again.

I'm pretty sure we tried this?

**Comment by skalia16** [comment]
> Font files are streamed in through a complicated binary .FCT file that we haven't really been able to decode. I'm actually not sure the .TTF/.OTF are used directly, they may only be parsed using information from the .FCT file.

Thanks for the reply.
But .FCT files seem to be just map files of the main font files .TTF/.OTF.
So, in theory, font changes are not possible without .TTF/.OTF files.
Since we cannot import these files, we cannot make changes.
Would it not be possible to make an import feature for these files?

**Comment by HENDRIX-ZT2** [comment]
You extract the fct. Replace a ttf/otf that is extracted along with your desired font. Inject the fct again, and it should inject the ttf/otf fonts along with it.

**Comment by skalia16** [comment]
> Fct'yi çıkarırsınız. Çıkarılan ttf/otf dosyasını istediğiniz yazı tipiyle değiştirin. Fct'yi tekrar enjekte ettiğinizde, onunla birlikte ttf/otf yazı tiplerini de enjekte etmelidir.

Bunu denememiştim doğru. Deneyip haber vereceğim. Teşekkürler.

> You extract the fct. Replace a ttf/otf that is extracted along with your desired font. Inject the fct again, and it should inject the ttf/otf fonts along with it.

I haven't tried it yet. I'll try and let you know. Thank you for your help.

**Comment by skalia16** [comment]
> You extract the fct. Replace a ttf/otf that is extracted along with your desired font. Inject the fct again, and it should inject the ttf/otf fonts along with it.

I haven't tried it yet. I'll try and let you know. Thank you for your help.

**Comment by skalia16** [comment]
@HENDRIX-ZT2 

To try it out, I changed a few files and repackaged them into the "Loc.ovl" file. Then when I unpacked it again, I found that the file I changed was still there.
 So doing it like you said works.
Thanks for your help mate :)
