### ISSUE TITLE
Decompiler error extracting LUA files with OVL Tool

### ISSUE THREAD

**Issue by DanyShady** [OpenNaja/cobra-tools#387]
Hi, sorry for my english and if this is not the correct place to ask for this but i didn't find the info i need anywhere and i need help.

For Jurassic World evolution 2, after I have used the OVL tool to extract the files, i'm trying to edit a simple line of one lua file with notepad, but the problem is that in the same file there are lines with the  DECOMPILER ERROR at.... so i can't inject the modified file in the game. (and if i delete the line the game crash)

Is there a way to decompile the lua files without having the DECOMPILER ERROR on them? or is there a way to Use the OVL tool only for extracting the lua files without decompiling them in order to being able to use another lua decompiler software to edit them?

How can i edit that file? Or this means that if a lua file shows the DECOMPILER ERROR at least in one line, does it means that it's totally impossible to edit that file by any method and the only option is to give up??

Thanks

**Comment by HENDRIX-ZT2** [comment]
> Is there a way to decompile the lua files without having the DECOMPILER ERROR on them? or is there a way to Use the OVL tool only for extracting the lua files without decompiling them in order to being able to use another lua decompiler software to edit them?
When decompilation fails, you can also get the compiled binary output. You have to activate debug mode for that, however. If you find a better decompiler, please tell!
