### ISSUE TITLE
MS2&blender problem

### ISSUE THREAD

**Issue by Binyu907** [OpenNaja/cobra-tools#389]
Every time I exported MS2 files from blender into the game, the game model would become strange, such as feet embedded in the ground, face distortion, etc. In addition, when I pull the far field of view in the game, the model will become the original model, and only when I pull the close field of view will it become the morphed model that I changed. All I'm doing is scaling up the model.
Can you tell me how to scale up a dinosaur model?

**Version Info:**
 - Python Version: [3.72}
 - Blender Version: [3.6]

**Comment by HENDRIX-ZT2** [comment]
Don't scale up the model in blender, as it will distort because you moved away from the bones. If you want to scale, you need to scale the anims too. There's a script that scales both the anims and model:

https://github.com/OpenNaja/cobra-tools/blob/master/experimentals/resize_manis.py

**Comment by Binyu907** [comment]
thank you. But i am sorry, i am not sure how to use this script. Do i drop it into "Content 0"? or others?

**Comment by Binyu907** [comment]
if filename.endswith(".ms2"):
  File "<blender_console>", line 1
            if filename.endswith(".ms2"):
        ^
IndentationError: unexpected indent

>>> 			ms2 = Ms2File()
  File "<blender_console>", line 1
                ms2 = Ms2File()
            ^
IndentationError: unexpected indent
Is this script input in blender? But it gave me the following error:
>>> 			ms2.load(file path, read_editable=True)
  File "<blender_console>", line 1
                ms2.load(filepath, read_editable=True)
            ^
IndentationError: unexpected indent

**Comment by Binyu907** [comment]
i think  this script should be inputed in blender. But there are nothing change after i exporting ms2 even i put script in blender.
