### ISSUE TITLE
Unable to open the tool(s) in the latest update

### ISSUE THREAD

**Issue by Robongio** [OpenNaja/cobra-tools#391]
Constantly getting this kind of result;
![Screenshot 2024-06-22 175014](https://github.com/OpenNaja/cobra-tools/assets/18617748/27255e0e-340f-432b-91d1-376ea3ca39de)

**Comment by HENDRIX-ZT2** [comment]
What's your python version?

**Comment by HENDRIX-ZT2** [comment]
I assume your python version is 3.7 or older. You need to use 3.11.

**Comment by Robongio** [comment]
> I assume your python version is 3.7 or older. You need to use 3.11.
Gosh darn it you're right! 
![Screenshot 2024-06-24 001944](https://github.com/OpenNaja/cobra-tools/assets/18617748/5c1d3718-27ed-451f-9d70-66ee4d7717cf)
Now the programming code works fine again, rookie mistake simply.
