### ISSUE TITLE
GUI - Convenience functions for folder view

### ISSUE THREAD

**Issue by ilodev** [OpenNaja/cobra-tools#392]
**Describe the bug**
Not exactly a bug, but it has been suggested having a game 'quick launch' button helps when debugging issues instead of having to use other type of shortcuts, since saving the ovl is usually the last thing you do before trying to launch the game.

- [x] add a 'play' button close to the game dropdown
  - [x] add a keyboard shortcut to launch the current selected game
  - [x] maybe add a checkbox to launch the game after saving the ovl all the time.
  - [x] investigate using steam api to launch the selected game if it is a steam game
     - https://discord.com/channels/680909673607463131/1020344989273821214/1281522669434568745
     - https://discord.com/channels/680909673607463131/1020344989273821214/1282375746769387541
  - [x] support different args per game
- [x] remove 'process folder' button
- [x] add batch context menu
- [x] improve show modded/official both switch
- [x] implement ovl file filter

**Comment by HENDRIX-ZT2** [comment]
Related: 
Could we get a prompt that comes up when we do Process Folder? I keep accidentially leaving it on, would be a good stop to have to keep from redoing old work ❤️
Also if a file is selected with process folder,,, could it default to processing the folder that the file itself is directly in, and not the entire ovldata folder? ❤️

**Comment by ilodev** [comment]
I'll be back in a couple of days, I can look into this stuff.

**Comment by ilodev** [comment]
We can maybe add a custom command line field then

**Comment by HENDRIX-ZT2** [comment]
For the command line options, yeah we probably should have a cfg value or something, as I've been getting crashes when supplying the jwe2 ones to the other games

> We can maybe add a custom command line field then
>
