### ISSUE TITLE
Exporting with 'Update rig' turned on results on in-game crash upon animal placement in Planet Zoo

### ISSUE THREAD

**Issue by SleepyEngi** [OpenNaja/cobra-tools#393]
**Describe the bug**
Exporting a model with "update rig" checked results in an in-game crash no matter if anything was actually rig edited.
No errors when exporting

**To Reproduce**
1. Export the ms2 with "Update rig" checked
2. It will now result in an in-game crash the instant the animal spawns in.

**Version Info:**
 - Python Version: [3.11]
 - Blender Version: [4.1]
 - Cobra Tools Version [3c3b24b - August 27, 2024]
 
 **Log Files:**
 - No errors within cobra
 
Mod file: 
https://we.tl/t-P8gJORS78i

Working & Broken example ms2 and ovls:
[Example files](https://github.com/user-attachments/files/16789997/WorkingBroken.zip)

**Commit testing**
August 28: Broken
August 2: Broken

**July 21**
aa926ca: Broken
f2b5847:Working

July 20: Working 
July 19: Working
July 2: Working
May 14: Working

**Comment by HENDRIX-ZT2** [comment]
Working again.
