### ISSUE TITLE
.manis not work

### ISSUE THREAD

**Issue by Riowars** [OpenNaja/cobra-tools#400]
After import .Manis file ( Attempt to import 1 .maniss, error found).
animation not work

**Comment by HENDRIX-ZT2** [comment]
Did you follow the instructions, especially these?
https://opennaja.github.io/cobra-tools/Guides/Plugin/Animations/

**Comment by HENDRIX-ZT2** [comment]
I've also added better error reporting that should make this more obvious. :)

**Comment by Riowars** [comment]
How to extract Aux to wav
