### ISSUE TITLE
AttributterError: 'int' object has no attribute write - while injecting .fgm

### ISSUE THREAD

**Issue by valdyr88** [OpenNaja/cobra-tools#41]
For Jurassic World Evolution, while injecting water.fgm into DefaultWater.ovl, AttributeError is catched:
 "int object has no attribute write"

the exception is generated in:  `def to_bytes(inst, data)`,  in file: /modules/inject.py

the simple fix is to just add:
```
	if isinstance(inst, int):
		return inst.to_bytes(4, 'little')
```
but for this, additional testing is needed to check if int to be injected needs to be 4 bytes (or 2, or possibly 8), and whether the storing of .ovl file is big or little endian.

**Comment by HENDRIX-ZT2** [comment]
Thanks for the report. I'm fairly sure ints should not go there, so while your fix might avoid the error it could cause unexpected behavior or bugs down the line.
to_bytes is a bit of a hacky mess at the moment. It should only get strings, byte strings or pyffi objects and return byte strings.

**Comment by Lavendellothar** [comment]
is there a fix for this actually? or can you tell me where to paste that code line?

**Comment by valdyr88** [comment]
> 
> 
> is there a fix for this actually? or can you tell me where to paste that code line?

Hey, this is a untested "fix" so it can have unintended consequences. But if you still wish to paste that you can open file: /modules/inject.py in some text editor, and scroll down to `def to_bytes(inst, data)` somewhere near the top of file. In that function there are multiple `if isinstance(...)`. Just add 
`	if isinstance(inst, int):
		return inst.to_bytes(4, 'little')`
right before 'with io.BytesIO()' and it should work.

@HENDRIX-ZT2 sry for replying to closed issue!

**Comment by HENDRIX-ZT2** [comment]
This commit https://github.com/OpenNaja/cobra-tools/commit/92094f354e8e59520e0aba1b08a497566b4c785a fixed it, just download the latest release.
