### ISSUE TITLE
add VoxelSkirt Injection and Extraction

### ISSUE THREAD

**Issue by KarI0s** [OpenNaja/cobra-tools#42]
FIle joins the material mask layers, the heightmap and asii file to create a terrain.
Propablly editable in some Voxel editor.

**Comment by HENDRIX-ZT2** [comment]
Give us a file format specification and we could do it.

**Comment by KarI0s** [comment]
FIle joins the material mask layers, the heightmap and asii file to create a terrain.
Propablly editable in some Voxel editor.

**Comment by HENDRIX-ZT2** [comment]
Fully implemented.
