### ISSUE TITLE
Font problem of the game

### ISSUE THREAD

**Issue by baoenzo** [OpenNaja/cobra-tools#43]
Hello, I searched google but haven't solved my problem yet.
I am looking for the font file of the game. Because I want to translate the game's language into Vietnamese but the game's font file does not support my language.
If you know where the font file is, please help me ...
Thank you so much.

**Comment by HENDRIX-ZT2** [comment]
Related: #11 
We don't really know anything about the font format at this point. It's apparently scaleform, ie. closed source, so probably difficult to edit once we can extract and inject its files.

**Comment by baoenzo** [comment]
Ồ, tôi tìm thấy phông chữ trong trò chơi. Nhưng công cụ của bạn dường như không trích xuất các tệp này. Các tập tin phông chữ ở định dạng. thuế nhà thầu
![image](https://user-images.githubusercontent.com/44154735/79083795-8891b300-7d5a-11ea-9fb7-80c64de66867.png)

**Comment by harlequinzeg0** [comment]
support for fonts added
