### ISSUE TITLE
OVl tool buffer?

### ISSUE THREAD

**Issue by Dannisaurus** [OpenNaja/cobra-tools#47]
I tried to use the OVL tool to extract OVL files from Jurassic world evolution, however when I try to unpack the files it comes up with an error saying it requires a buffer of 4 bytes. I cannot find answers for this anywhere and I have no clue how to solve this

**Comment by HENDRIX-ZT2** [comment]
Are you running the latest game version and the latest release of the tools?

**Comment by Dannisaurus** [comment]
Latest tools, not the latest game version

**Comment by HENDRIX-ZT2** [comment]
Must be the latest game version too, the pirated early game version is not supported.
