### ISSUE TITLE
This app can't run on your PC

### ISSUE THREAD

**Issue by Ironcarnage101** [OpenNaja/cobra-tools#49]
I don't know what's going on, I've tried looking up a solution. But nothing's worked. I keep running into this and frankly it's getting annoying.
![image](https://user-images.githubusercontent.com/64900353/81168783-c5646900-8feb-11ea-8d15-6440325912ef.png)

I've got a 64 bit computer and I've extracted the files but again, nothing's working?

**Comment by HENDRIX-ZT2** [comment]
This is due to your python installation, has nothing to do with the tools.

**Comment by Ironcarnage101** [comment]
So I should upgrade to the newest version of Python?

**Comment by HENDRIX-ZT2** [comment]
Yeah you can do that.
