### ISSUE TITLE
Jurassic world evolution Cobra Tools bug

### ISSUE THREAD

**Issue by sovfx** [OpenNaja/cobra-tools#50]
Struct.error unpack requires a bytes object of length 4 (Error)

every time I try to open .OVL file which is of no more than 5MB

please help
![111](https://user-images.githubusercontent.com/65479283/82136013-b0c37480-9826-11ea-99c0-8174f96b8db7.PNG)

**Comment by HENDRIX-ZT2** [comment]
Latest tools version, latest game version?
