### ISSUE TITLE
OVL Tool wont open

### ISSUE THREAD

**Issue by TheIronist** [OpenNaja/cobra-tools#51]
Hello Guys,

everytime i want to open the ovl_tool_gui.py the thing automaticly  closes in seconds without any error messages.

Dunno what i did wrong. I hope you can help me out.

Thanks in advance.

Kind regards

**Comment by harlequinzeg0** [comment]
either didnt follow install instructions correctly (like adding the python install to path), or your windows is being weird and you have to run the program through command prompt
