### ISSUE TITLE
GUI not launching - No module named 'pyffi_ext.formats'

### ISSUE THREAD

**Issue by SarahGG** [OpenNaja/cobra-tools#56]
Hello!

I seem to be having issues getting the GUI to come up. I have python 3.6 x64, and have the pyffi folder copied into the blender lib from my python lib. When I double click the launching in cobra-tools-master, my cmd quickly opens and closes. When I run the program through my shell, I get this:

```
PS C:\Users\Sarah\Desktop\cobra-tools-master> python ovl_tool_gui.py
Traceback (most recent call last):
  File "ovl_tool_gui.py", line 9, in <module>
    from pyffi_ext.formats.ovl import OvlFormat
ModuleNotFoundError: No module named 'pyffi_ext.formats'
```

Is anyone familiar with what step I've missed? I've combed through both a video tutorial for Plazet Zoo modding and the installation READMEs for bother cobra-tools-master and cobra-blender and can't find a step that I've missed. I've traced my steps twice now, restarted in between, still no dice. I have to be looking over it somewhere.

**Comment by HENDRIX-ZT2** [comment]
You have to download the release build (cobra-tools.zip), not the source code (cobra-tools-master.zip).

**Comment by SarahGG** [comment]
That's done the trick!

![image](https://user-images.githubusercontent.com/23173393/89738316-89ef9580-da45-11ea-817f-672835267204.png)

For anyone who may have this similar issue later, you can find the correct file to download here:
https://github.com/OpenNaja/cobra-tools/releases
