### ISSUE TITLE
AUX file support

### ISSUE THREAD

**Issue by harlequinzeg0** [OpenNaja/cobra-tools#58]
The aux files are super similar to standard ones, just the BKHD header is different from standard
http://wiki.xentax.com/index.php/Wwise_SoundBank_(*.bnk)#BKHD_section

new header is:
BKHD, length of section, version, id1?, id2?, constant, constant, zeroes

Can easily extract audio into wem files and convert either to uncompressed wav with WWISE or ogg with ww2ogg using following settings: 
```
ww2ogg.exe audio.wem --pcb packed_codebooks_aoTuV_603.bin
revorb.exe audio.ogg
```
will need to convert back to wem (can use WWise if using wavs) and inject new wems into the the aux archive with a custom injector.

**Comment by HENDRIX-ZT2** [comment]
We've implemented it.
