### ISSUE TITLE
Elite Dangerous support

### ISSUE THREAD

**Issue by tetTris11** [OpenNaja/cobra-tools#61]
Hi, I recently discovered this tool and decided to see if I could get stuff from one of Frontier's other games "Elite Dangerous"

Now keep in mind, as of update 2.4 way back in mid 2017 they drastically changed how the file formatting is done (more than likely to prevent people digging around in the files and finding spoiler content) as apposed to conventional folders and naming schemes every file has its extension removed, named a long line of random numbers and and placed in 1 of 16 subfolders. (but that's a story for another day)

But not all is lost as Steam keeps backups of previous versions of games stored on their servers which with the right know how (Depot downloader) you can force download. I used this to download a version of Elite right before update 2.4 and use the tools on those files.
To no one's surprise it didn't work so I've come to see if anything can be done.

Below is a MEGA link to a small handful of files, included are 2 ships, a surface drone, a small handful of pilot related stuff (for the sake of testing rigged models) and the entire audio folder because it referenced almost everything when I tried it
https://mega.nz/folder/IRgACIIT#jfatj3pYygRdqXQQpPVAUw

Thank you for your time.

**Comment by HENDRIX-ZT2** [comment]
Good news: archive data is read into memory just fine according to our file format specs (same data version as JWE and PZ).
Bad news: the internal data fragmentation and organization is different from JWE & PZ, so that the data fragments are not properly mapped to proper files using our code. If we decided to code an alternative fragment mapping, I wonder how we could tell these games apart with code.

Are the files after the update still OVLs, starting with `FRES` in hex?

**Comment by HENDRIX-ZT2** [comment]
They've probably replaced proper names with hashes for the update, lol

**Comment by tetTris11** [comment]
I'm not sure (Hex coding isn't my area of expertise) though I've updated the MEGA link with a folder containing a handful of post 2.4 files (in the 0e folder) I've also put in a basic comparison picture of what the folder/file structure looked like before and after 2.4 (if it helps).

Another thing I feel worth mentioning is ED is currently 75% off on Steam (making it around $7 to $10 as apposed to around $40 depending on where you live) could be a good opportunity to get it to have a better look at everything

**Comment by harlequinzeg0** [comment]
![image](https://user-images.githubusercontent.com/2275463/95996149-f85f2400-0df7-11eb-9c3d-1abe7a9fc43d.png)

I'm sorry to say that they encrypted their entire game archive into the unreadable FREA format. it is not possible to mod the game anymore past update 2.4, likely to hide hidden content as you mentioned.

**Comment by tetTris11** [comment]
Sorry to bring this up so late (I completely forgot) but while nothing can be done with anything post 2.4, could it still be possible to at least extract stuff from any pre-2.4 files?

**Comment by HENDRIX-ZT2** [comment]
It is technically possible but would require custom logic to reconstruct the files from the fragmented archive data. This is tricky to figure out and could introduce issues with the code that handles this for jwe and pz. So we won't do that. 
If you want the files, you gotta write the fragment logic.

**Comment by HENDRIX-ZT2** [comment]
I've looked at ED ovls again and they share some logic with Planco. Managed to get DDS export working without messing up the rest.
The other formats are slightly different from what we know.

**Comment by HENDRIX-ZT2** [comment]
Added support for fgms (materials) too.

**Comment by harlequinzeg0** [comment]
All  elite dangerous modding support is permanently to remain unsupported going forward to comply with Frontier
