### ISSUE TITLE
Problem with ovl_tool_gui.py

### ISSUE THREAD

**Issue by DinoOtaku** [OpenNaja/cobra-tools#62]
Hello, I have a problem, why when I click on ovl_tool_gui.py, a window appears and then closes.

**Comment by jamesmiller20110** [comment]
mines too what happend

**Comment by mra144910** [comment]
I'm having this issue as well. I don't get why I can't get this to work even after following every step exactly as described

**Comment by DinoOtaku** [comment]
The problem is solved

**Comment by sed131** [comment]
how did you fix it man pls help

**Comment by DinoOtaku** [comment]
Hi, I couldn't install imageio because my version of python was too recent
so I installed an old one.

**Comment by DinoOtaku** [comment]
And after Cobra Tools worked

Le dim. 8 nov. 2020 à 09:01, Alexis KLEIN <kleinalexis67@gmail.com> a
écrit :

> Hi, I couldn't install imageio because my version of python was too recent
> so I installed an old one.
>
