### ISSUE TITLE
unpack requires a buffer of 4 bytes

### ISSUE THREAD

**Issue by jamesmiller20110** [OpenNaja/cobra-tools#63]
how do you fix this problem it says  :struct.error: unpack requires a buffer of 4 bytes pls tell me

**Comment by HENDRIX-ZT2** [comment]
Which file which game versions which tool? Complete error log?

**Comment by jamesmiller20110** [comment]
it was the cobra tool to mod jurassic world but when i select and ovl file it says error unpack requires a buffer of 4 bytes right now i could have taken a screenshot but your tool isnt working everytime i click it it opens a command prop and then closes so can you also fix that also

**Comment by HENDRIX-ZT2** [comment]
Try the latest code: https://github.com/OpenNaja/cobra-tools/archive/master.zip

**Comment by jamesmiller20110** [comment]
um it dosent have the ovl tool bat so theres no use what should i do with it

**Comment by HENDRIX-ZT2** [comment]
Double click ovl_tool_gui.py to run it with the python launcher. You should have installed it with python.

**Comment by jamesmiller20110** [comment]
i did but when a command promt opens it shuts down in half a second then nothing happens actually wait let me show you the vid here :https://www.youtube.com/watch?v=lrnf12QnqU0&feature=youtu.be

**Comment by jamesmiller20110** [comment]
i did but when i open it a command promt comes then closes in half a second and nothing happens actually wait let me show you the vid open the zip file and it will have the video

**Comment by HENDRIX-ZT2** [comment]
You are missing the required python dependencies. Follow the installation instructions.

**Comment by jamesmiller20110** [comment]
um can you pls make a video of how to do it cus im confused i followed everything bestinslot has done but it still didnt work so you know the best so can you pls i will tell all my subscribers to subscribe to your channel pls

**Comment by HENDRIX-ZT2** [comment]
No.
There's a video tutorial right here:
https://www.youtube.com/watch?v=DY_o_yyIa6E&list=PLhEZgU4FR_VW3GbX1DFBColB4O-6iNHd5&index=3
Although it's outdated, the process is still the same.

**Comment by jamesmiller20110** [comment]
ok

**Comment by jamesmiller20110** [comment]
here check this video 
:https://youtu.be/MttH77K3S00

**Comment by jamesmiller20110** [comment]
hello pls respond

**Comment by HENDRIX-ZT2** [comment]
You have installed it correctly. It appears that your game version is not the latest. Only the current version is supported.
