### ISSUE TITLE
OVL - Support JWE on Switch

### ISSUE THREAD

**Issue by Kendaman** [OpenNaja/cobra-tools#65]
"Error -3 while decompressing data: invalid stored block length"
The other day, the complete edition was released on switch. Unable to load ovl file.
It is possible to provide samples as needed.

**Comment by HENDRIX-ZT2** [comment]
For which game?
Need more information, ovl (+ovs) samples help.

**Comment by Kendaman** [comment]
[Ankylosaurus.zip](https://github.com/OpenNaja/cobra-tools/files/5493602/Ankylosaurus.zip)
here's sample

**Comment by BigBoss0674** [comment]
Hello! I have same problem with Switch version of Jurassic World Evolution. I need to modify just 1 file - "Config.ovl" Here it is:
Is posible to make support for Switch version?
[Config.zip](https://github.com/OpenNaja/cobra-tools/files/5494678/Config.zip)

**Comment by HENDRIX-ZT2** [comment]
Appears to be a different compression format, possibly oodle. Will probably not be easy to support, if possible at all.

**Comment by BigBoss0674** [comment]
Maybe able to extract files and pack them with PC method compression? I think, Switch version understand PC method, because game is load when i replace file. Or this is not be easy too?

**Comment by HENDRIX-ZT2** [comment]
Oodle decompression is implemented. Config extracts properly. Ankylo has trouble loading, internal archive structure appears to be different.

**Comment by BigBoss0674** [comment]
"Config extracts properly" but how? i have error -3 whe i try to open file :(

**Comment by HENDRIX-ZT2** [comment]
Download this: https://github.com/OpenNaja/cobra-tools/archive/master.zip

**Comment by BigBoss0674** [comment]
HENDRIX-ZT2, OMG! Thank you so much! With that version of tool i extracted Switch Config (game crash after packing but its not a problem)

**Comment by HENDRIX-ZT2** [comment]
It's saving as ZIP instead of oodle compression, thus it breaks. Not sure how to implement oodle compression.

**Comment by HENDRIX-ZT2** [comment]
I've coded oodle compression, just need to implement it so that the proper compression is triggered on saving.

**Comment by HENDRIX-ZT2** [comment]
Switch config should be editable with latest source code.

**Comment by BigBoss0674** [comment]
I just took all the text from Switch and copy it to PC config, and it works, i already make a mod.
But yes, now it works! Unpacking and Injecting to Switch config works, game loaded and works fine. Thank You so much again! :)
If you can, here is one more interesting file to me - Main.ovl
[Main.zip](https://github.com/OpenNaja/cobra-tools/files/5504839/Main.zip)
Cannot open properly and tool did not extract anything.

**Comment by HENDRIX-ZT2** [comment]
Currently don't have time to investigate the new switch format in detail.

**Comment by HENDRIX-ZT2** [comment]
The lua from Matanceros does not decompile properly. Only luas without decompilation errors can be injected. I've added a check that prevents this.

**Comment by dinoking27** [comment]
i also want to switch OVL with JWE2 because i want to is it possible to click on the config of the folder from ovl util if thats possible?

**Comment by HENDRIX-ZT2** [comment]
> i also want to switch OVL with JWE2 because i want to is it possible to click on the config of the folder from ovl util if thats possible?

???

**Comment by dinoking27** [comment]
> > i also want to switch OVL with JWE2 because i want to is it possible to click on the config of the folder from ovl util if thats possible?
> 
> ???

how do I change it from MDL2 to OVL that's all that's what I'm trying to say

**Comment by HENDRIX-ZT2** [comment]
Technically it's working. Some mimes may need to be made file-version dependant to work correctly
