### ISSUE TITLE
Ovl tool doesn't open - bugged numpy dependency on Windows

### ISSUE THREAD

**Issue by sed131** [OpenNaja/cobra-tools#66]
when i open the ovl tool it opens 1 second and closes immediately please help

**Comment by HENDRIX-ZT2** [comment]
Follow the installation instructions.

**Comment by sed131** [comment]
i have
but it still doesn't work

**Comment by Kendaman** [comment]
try python
pip install PyFFI==2.2.4.dev3

**Comment by sed131** [comment]
i have

**Comment by sed131** [comment]
still dont work

**Comment by Kendaman** [comment]
try drag to python.exe

**Comment by HENDRIX-ZT2** [comment]
Try with this one:
https://github.com/OpenNaja/cobra-tools/archive/master.zip

And post the console log if it still does not work (it will now stay open for 15 seconds incase something went wrong).

**Comment by sed131** [comment]
it opens and after like 20 sec it closes

**Comment by HENDRIX-ZT2** [comment]
Copy & paste the error log that appears!

**Comment by sed131** [comment]
** On entry to DGEBAL parameter number  3 had an illegal value
 ** On entry to DGEHRD  parameter number  2 had an illegal value
 ** On entry to DORGHR DORGQR parameter number  2 had an illegal value
 ** On entry to DHSEQR parameter number  4 had an illegal value
Traceback (most recent call last):
  File "C:\Users\45405\Desktop\cobra-tools-master\ovl_tool_gui.py", line 8, in <module>
    import numpy as np
  File "C:\Users\45405\AppData\Local\Programs\Python\Python36\lib\site-packages\numpy\__init__.py", line 305, in <module>
    _win_os_check()
  File "C:\Users\45405\AppData\Local\Programs\Python\Python36\lib\site-packages\numpy\__init__.py", line 302, in _win_os_check
    raise RuntimeError(msg.format(__file__)) from None
RuntimeError: The current Numpy installation ('C:\\Users\\45405\\AppData\\Local\\Programs\\Python\\Python36\\lib\\site-packages\\numpy\\__init__.py') fails to pass a sanity check due to a bug in the windows runtime. See this issue for more information: https://tinyurl.com/y3dm3h86

**Comment by HENDRIX-ZT2** [comment]
According to the link, recommended solution is to run:
pip install numpy==1.19.3

**Comment by sed131** [comment]
it worked thx you so much
