### ISSUE TITLE
Can't unpack ovl file of JWE

### ISSUE THREAD

**Issue by akonymike2014** [OpenNaja/cobra-tools#68]
Hi @HENDRIX-ZT2 ,
I downloaded your cobra-tools-master and another version. But when I open my dinosaur ovl, it's show a error "unpack requires a buffer of 4 bytes"
Hope you fix it !! 
Thanks you

![image](https://user-images.githubusercontent.com/74422925/99097292-fd3b1180-2609-11eb-9a43-bcc894933436.png)

**Comment by HENDRIX-ZT2** [comment]
Which game version is that?

**Comment by akonymike2014** [comment]
[Allosaurus.zip](https://github.com/OpenNaja/cobra-tools/files/5538166/Allosaurus.zip)
This is ovl file for testing !!

**Comment by akonymike2014** [comment]
Sorry, i am NOOB, how to find game version of JWE?

**Comment by HENDRIX-ZT2** [comment]
Idk, but I do know that only the current version is supported. The game formats have evolved a bit and we can only support the current version. If you have a pirated, outdated copy you're on your own.
