### ISSUE TITLE
tex files not unpacking

### ISSUE THREAD

**Issue by jamesmiller20110** [OpenNaja/cobra-tools#69]
hey i wanted to report that the tex files arent unpacking i dont know why but pls reply

**Comment by jamesmiller20110** [comment]
the tex filed do get opened but when i unpack then to a folder only mdl2 and matcol and everything else comes exept for tex files and also the animations an matierials get a error when i import them to blender i dont know why but if you dont understand then tell  me il send you a video link

**Comment by HENDRIX-ZT2** [comment]
For texconv you probably haven't installed the right version of MS visual c redistributable.
Animations can't be imported.

**Comment by jamesmiller20110** [comment]
so can you tell me how to install it please

**Comment by HENDRIX-ZT2** [comment]
Follow the instructions: https://github.com/OpenNaja/cobra-tools
