### ISSUE TITLE
'OvsFile' object has no attribute 'is_pz'

### ISSUE THREAD

**Issue by SzNorbi91** [OpenNaja/cobra-tools#73]
Hi,
I want to ask for help. after I compress the Planet Zoo loc file back, I get this message on save and it didn't save. What is the problem?

'OvsFile' object has no attribute 'is_pz'

Thanks

**Comment by HENDRIX-ZT2** [comment]
I believe I've fixed it - could you check with the latest version?

**Comment by HENDRIX-ZT2** [comment]
@SzNorbi91 This one:
https://github.com/OpenNaja/cobra-tools/archive/master.zip

**Comment by SzNorbi91** [comment]
Hi!

Thanks it works.

HENDRIX-ZT2 <notifications@github.com> írta:
>
>@SzNorbi91 This one:
>https://github.com/OpenNaja/cobra-tools/archive/master.zip
>
>&mdash;You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
>
