### ISSUE TITLE
Not work edit the Txt 

### ISSUE THREAD

**Issue by Antrixs** [OpenNaja/cobra-tools#80]
I can not

Edit the Txt files relevant to replacing the species.
inject the Txt files and save the new Loc.OVL.
replace the stock Loc.OVL and back it up.

game of epic game

The program displays such a message

The following type - map pairs were found:
Scanning C:/Users/J/Music/Nowy folder (6) for ovl files

Injecting...
Injecting frontend_campaigntitle.txt
Done!
Writing OVL
'BinaryStream' object has no attribute 'version_flag'
Done!

The problem is only with the program version

https://github.com/OpenNaja/cobra-tools/archive/master.zip

która znajduje się tu w opise .

Installation
Get the latest source code here and unzip to a folder of your choice. You need to have installed:

https://codeload.github.com/OpenNaja/cobra-tools/zip/master

program must be downloaded current version main page

https://codeload.github.com/OpenNaja/cobra-tools/zip/master

Please correct

**Comment by HENDRIX-ZT2** [comment]
Download https://github.com/OpenNaja/cobra-tools/archive/master.zip again, this has already been fixed today.

**Comment by Antrixs** [comment]
Works thank you
