### ISSUE TITLE
name 'is_ed' is not defined

### ISSUE THREAD

**Issue by HappyRogue658** [OpenNaja/cobra-tools#81]
I'm trying to unpack an OVL file. I'm getting this error.

Writing sinoceratops.pnormaltexture.dds

An exception occurred while extracting sinoceratops.pnormaltexture.tex
name 'is_ed' is not defined
Traceback (most recent call last):
  File "H:\Projects\Jurassic World Evolution Modding\cobra-tools-master\modules\extract.py", line 132, in extract
    extract_kernel(out_paths, sized_str_entry, archive, out_dir_func, show_temp_files, progress_callback)
  File "H:\Projects\Jurassic World Evolution Modding\cobra-tools-master\modules\extract.py", line 78, in extract_kernel
    paths.extend(write_dds(archive, entry, show_temp_files, out_dir_func))
  File "H:\Projects\Jurassic World Evolution Modding\cobra-tools-master\modules\formats\DDS.py", line 85, in write_dds
    if is_pc(archive.ovl) or is_ed(archive.ovl):
NameError: name 'is_ed' is not defined
Files not extracted due to error:
         sinoceratops.fgm
         sinoceratops_variant_01.fgm
         sinoceratops_variant_02.fgm
         sinoceratops_variant_03.fgm
         sinoceratops_variant_04.fgm
         sinoceratops_variant_05.fgm
         sinoceratops_variant_default.fgm
         sinoceratops.materialcollection
         sinoceratopsvariants.materialcollection
         sinoceratops.ms2
         sinoceratops_skeleton_.ms2
         sinoceratops.pbasediffusetexture.tex
         sinoceratops.playered_blendweights.tex
         sinoceratops.pbasepackedtexture.tex
         sinoceratops.playered_warpoffset.tex
         sinoceratops.pnormaltexture.tex

I'm using these versions:
Latest Cobra tools
Python 3.7.9 x64 with imageio, pyqt5
Microsoft Visual C++ 2013 Redistributable (x86)  12.0.40660
Microsoft Visual C++ 2015-2019 Redistributable (x64)  14.28.29334
Jurassic World Evolution 1.12.6.54907, Epic version

**Comment by leandrolima88** [comment]
NameError: name 'is_ed' is not defined
Files not extracted due to error:
	 tyrannosaurus01.fgm
	 tyrannosaurus.fgm
	 tyrannosaurus_variant_01.fgm
	 tyrannosaurus_variant_02.fgm
	 tyrannosaurus_variant_03.fgm
	 tyrannosaurus_variant_04.fgm
	 tyrannosaurus_variant_05.fgm
	 tyrannosaurus_variant_default.fgm
	 tyrannosaurusvariants01.materialcollection
	 tyrannosaurusvariants.materialcollection
	 tyrannosaurus.materialcollection
	 tyrannosaurus.ms2
	 tyrannosaurus_skeleton_.ms2
	 tyrannosaurus.playered_warpoffset.tex
	 tyrannosaurus.pbasepackedtexture.tex
	 tyrannosaurus01.pbasecolourtexture.tex
	 tyrannosaurus.pnormaltexture.tex
	 tyrannosaurus.pbasediffusetexture.tex
	 tyrannosaurus.playered_blendweights.tex


Other errors:
File "C:\...cobra-tools-master\modules\formats\FGM.py", line 33, in write_fgm
    raise AttributeError("Fgm length is wrong")

Using Epic Games version...

**Comment by HENDRIX-ZT2** [comment]
Fixed.
