### ISSUE TITLE
Unweighted vertices

### ISSUE THREAD

**Issue by jjdp0** [OpenNaja/cobra-tools#86]
I am sincerely sorry for posting so many questions. To whoever is reading this, forgive me if I have agitated you.

But I digress. I fixed the extraneous vertex groups problem, but the unweighted vertices issue has appeared. Tried using weight paint _again_  still no dice.

**Comment by HENDRIX-ZT2** [comment]
This is not an issue. You can use pose mode and move the root node. If any vertices do not move along, these are the unweighted ones.

**Comment by jjdp0** [comment]
Ok, but how do I weigh them? Do I use weight paint?

**Comment by HENDRIX-ZT2** [comment]
Yes you do. It does if you do it correctly. Look it up.
