### ISSUE TITLE
hi! thank you for creating the mode tool, but unfortunately i just can't use it

### ISSUE THREAD

**Issue by dvir1400** [OpenNaja/cobra-tools#87]
I will explain, I have python+ the c++ packages, but I just can't seem to download the python libraries, I don't know what to do. here is a picture of what I see:

![Capture](https://user-images.githubusercontent.com/77443467/104709255-5d902180-5727-11eb-91d6-79f247ccc4c6.PNG)
  
the same error is going on when trying to install pyqt5

can you please help me?
I would even allow team viewer so you can control my pc and download it, I just don't know what to do

**Comment by dvir1400** [comment]
sorry if I seem a little stupid to ask this but maybe if someone have the lib's and python installed he can zip it and send it to me?
if it works
I just really want to make and add some modes and this tool seems awesome, I just don't know anything in python

**Comment by dvir1400** [comment]
I mean zip the entire python37 folder and send, if it is possible and will work

**Comment by HENDRIX-ZT2** [comment]
If i had to guess, your antivirus is blocking pip.
