### ISSUE TITLE
The blender plugin doesn't work

### ISSUE THREAD

**Issue by PanekPro** [OpenNaja/cobra-tools#88]
When I try to use the blender plugin to import .mdl2, it closes and disables the blender plugin addon. what to do?

**Comment by PanekPro** [comment]
Why did you remove cobra blender?

**Comment by HENDRIX-ZT2** [comment]
It's outdated. Use cobra-tools instead. ;)

**Comment by PanekPro** [comment]
but how?

**Comment by PanekPro** [comment]
When I import them as a addon it doesn't work.

**Comment by HENDRIX-ZT2** [comment]
It does.

**Comment by PanekPro** [comment]
so what zip I should import to blender? cobra-master.zip or cobra-tools-1.9.zip?

**Comment by PanekPro** [comment]
when I use cobra-master.zip, this happens:
![image](https://user-images.githubusercontent.com/68421804/104957689-e977a700-59ce-11eb-9ada-a1ea76af37d3.png)

**Comment by HENDRIX-ZT2** [comment]
master.
The bug appears because you're trying to import a mdl2 that has been exported from an older version of cobra tools. Always use the same version of cobra tools for extracting and blender.

**Comment by PanekPro** [comment]
so i should install cobra tools 1.9.1?

**Comment by PanekPro** [comment]
when I did that blender just closed

**Comment by HENDRIX-ZT2** [comment]
No you **must** use master.zip for both.

**Comment by PanekPro** [comment]
Oh sorry didn't noticed that sorry for bothering
