### ISSUE TITLE
pip doesn`t work 

### ISSUE THREAD

**Issue by lolomon1049** [OpenNaja/cobra-tools#89]
![image](https://user-images.githubusercontent.com/77808822/105411207-64d99280-5c33-11eb-9084-dea59de67f11.png)
sorry for german the text means: the command pip either its wrote wrong or couldn`t be find.

**Comment by HENDRIX-ZT2** [comment]
Read the installation instructions.

**Comment by lolomon1049** [comment]
i have multible times

**Comment by lolomon1049** [comment]
> Read the installation instructions.

i have multible times

**Comment by HENDRIX-ZT2** [comment]
Bei der python installation musst du die option anklicken, es zum Pfad hinzuzufügen.

**Comment by lolomon1049** [comment]
> Bei der python installation musst du die option anklicken, es zum Pfad hinzuzufügen.

i have

**Comment by HENDRIX-ZT2** [comment]
No you have not. If you had it would work.
