### ISSUE TITLE
add Lua Injection and Extraction

### ISSUE THREAD

**Issue by harlequinzeg0** [OpenNaja/cobra-tools#9]

**Comment by harlequinzeg0** [comment]
Hash checks seemingly disabled, this is able to be worked on now

**Comment by HENDRIX-ZT2** [comment]
Preliminary injection of compiled lua implemented by @harlequinzeg0 
Automatic decompilation & compilation as is done for DDS / PNG workflow still missing.

**Comment by harlequinzeg0** [comment]
will need custom luadec and luac programs. 5.3 format, compiled header has implied integer length so it shows up as 04,04,08,04 instead of 04,04,04,08,04. 

there is also custom inherent types added to the animal luas. known types are vector3 floats and possibly quaternions

**Comment by harlequinzeg0** [comment]
currently do have a luadec and luac that can decompile and compile a handful of non animal lua files

**Comment by toxicantidote** [comment]
If this works, it'd be great for fixing up some irritating bugs that Frontier don't seem interested in fixing. I'm looking at you animal boxing bug.

**Comment by HENDRIX-ZT2** [comment]
Only a select few simple luas decompile properly at the moment, so this is a bit out of reach right now 😢

**Comment by harlequinzeg0** [comment]
by temporarily changing vector3 types (0A,00) to strings (04,0C) and running unluac.jar i can generate plaintext lua files. running luac on them and editing the vector3 back from string type seems to then have a working compiled lua

**Comment by harlequinzeg0** [comment]
basic decompiler for non vect3 luas implemented

**Comment by harlequinzeg0** [comment]
sso lua support technically added, just dont have a compiler, need to test if plain text lua's work ingame

**Comment by HENDRIX-ZT2** [comment]
Plaintext luas work just fine, so closed.
