### ISSUE TITLE
Can't install Add-ons import_mdl2 in Blender

### ISSUE THREAD

**Issue by eurovietnam** [OpenNaja/cobra-tools#92]
I installed Blender new version.
i can't install add-on import_mdl2 (export_mdl2) in Blender

I have video error, help me please ! Thanks you very much !
[https://youtu.be/VJGNIVEDW9E](url)

**Comment by HENDRIX-ZT2** [comment]
Install this zip file instead - do not unzip:
https://github.com/OpenNaja/cobra-tools/archive/master.zip

**Comment by eurovietnam** [comment]
I can do it
thank you very much !
