### ISSUE TITLE
When Export -> Cobra Model (.Mdl2) -> error "you must open an existing mdl2 for exporting" help me !

### ISSUE THREAD

**Issue by eurovietnam** [OpenNaja/cobra-tools#95]
When Export -> Cobra Model (.Mdl2) -> error "you must open an existing mdl2 for exporting" help me !
Thank you very much !!!

**Comment by HENDRIX-ZT2** [comment]
Do what it says.

**Comment by eurovietnam** [comment]
i don't understand
help me, please !
