### ISSUE TITLE
Issue Trying to Enable the Blender Plugin

### ISSUE THREAD

**Issue by bobmot124** [OpenNaja/cobra-tools#98]
So I easily installed the addon, but then when I tried activating it blender gave me this error, it might be because I am using portable blender, but IDK why that would have changed anything.
![Screenshot 2021-02-15 095410](https://user-images.githubusercontent.com/68389647/107979847-1db19980-6f74-11eb-983d-f6b685c86798.png)

**Comment by HENDRIX-ZT2** [comment]
Delete any older versions of cobra tools from your blender and any older blender versions you may have.

**Comment by dinoking27** [comment]
i was also having the same issue after I deleted the older version of cobra tools and it still says the same thing
